AAEmu.Game/Models/Game/Char/Inventory.cs
SQL/aaemu_game.sql

Added code to save/load item grades from items db.
We will need this later when we start adding regrades.

Save item grades

---

AAEmu.Game/Core/Managers/FriendMananger.cs
AAEmu.Game/Core/Managers/Id/FriendIdMananger.cs
AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Core/Packets/C2G/CSAddFriendPacket.cs
AAEmu.Game/Core/Packets/C2G/CSDeleteFriendPacket.cs
AAEmu.Game/Core/Packets/C2G/CSSelectCharacterPacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterFriends.cs
AAEmu.Game/Models/Game/Friend.cs
AAEmu.Game/Program.cs
AAEmu.Game/Scripts/Commands/Position.cs
SQL/aaemu_game.sql
SQL/updates/12.02.2019_aaemu_game.txt

- Basic Function [All Done]
- Friend List Window [7/8 Done]
- Chat [All Done]
- Party [0/1]

[Game] -Add: Friend list functions

---

AAEmu.Game/Core/Managers/FamilyManager.cs
AAEmu.Game/Core/Managers/FriendMananger.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs

Changed functions name to match its purpose.

[Game] -Friend: function name fix

---

README.md

Добавил ссылку на сайт https://aaemu.info

Добавил ссылку на сайт https://aaemu.info

---

SQL/aaemu_game.sql
SQL/updates/17.02.2019_aaemu_game.sql

AAEmu_Game table update.
**Default dump table structure by Navicat.**

[SQL] -Update tables

---

SQL/aaemu_game.sql
SQL/updates/18.02.2019_aaemu_game.sql

Collate fixed to be compatible with older versions of mysql.

[SQL] -Fix collate compatibility

---

AAEmu.Game/Core/Managers/PortalManager.cs
AAEmu.Game/Core/Network/Game/GameNetwork.cs
AAEmu.Game/Core/Packets/C2G/CSCanStartTradePacket.cs
AAEmu.Game/Core/Packets/C2G/CSDestroyItemPacket.cs
AAEmu.Game/Core/Packets/C2G/CSSellItemsPacket.cs
AAEmu.Game/Core/Packets/C2G/CSStartTradePacket.cs
AAEmu.Game/Core/Packets/C2G/CSThisTimeUnpackItemPacket.cs
AAEmu.Game/Core/Packets/G2C/SCCanStartTradePacket.cs
AAEmu.Game/Core/Packets/G2C/SCCannotStartTradePacket.cs
AAEmu.Game/Core/Packets/G2C/SCOtherTradeItemPutupPacket.cs
AAEmu.Game/Core/Packets/G2C/SCOtherTradeItemTookdownPacket.cs
AAEmu.Game/Core/Packets/G2C/SCOtherTradeMoneyPutupPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeCanceledPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeItemPutupPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeItemTookdownPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeLockUpdatePacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeMadePacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeMoneyPutupPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeOkUpdatePacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeStartedPacket.cs
AAEmu.Game/Models/Game/OpenPortal/OpenPortalEffects.cs
AAEmu.Game/Models/Game/Skills/Effects/OpenPortalEffect.cs
AAEmu.Game/Scripts/Commands/Move.cs

Update and Fix portals.
Update on trade.
Add SC trade packets.
Fix some CS/SC packets.
Fix /move command.

[Game] -portal fix/-trade updates/-add new packets

---

AAEmu.Game/Core/Managers/Id/TradeIdManager.cs
AAEmu.Game/Core/Managers/PortalManager.cs
AAEmu.Game/Core/Managers/TradeManager.cs
AAEmu.Game/Core/Packets/C2G/CSCanStartTradePacket.cs
AAEmu.Game/Core/Packets/C2G/CSCancelTradePacket.cs
AAEmu.Game/Core/Packets/C2G/CSCannotStartTradePacket.cs
AAEmu.Game/Core/Packets/C2G/CSDestroyItemPacket.cs
AAEmu.Game/Core/Packets/C2G/CSPutupTradeItemPacket.cs
AAEmu.Game/Core/Packets/C2G/CSPutupTradeMoneyPacket.cs
AAEmu.Game/Core/Packets/C2G/CSSaveTutorialPacket.cs
AAEmu.Game/Core/Packets/C2G/CSStartTradePacket.cs
AAEmu.Game/Core/Packets/C2G/CSTakedownTradeItemPacket.cs
AAEmu.Game/Core/Packets/C2G/CSTradeLockPacket.cs
AAEmu.Game/Core/Packets/C2G/CSTradeOkPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTradeMadePacket.cs
AAEmu.Game/Program.cs

[Game] -Trading system

---

AAEmu.Game/Core/Packets/C2G/CSRequestHouseTaxPacket.cs
AAEmu.Game/Core/Packets/G2C/SCAskImprisonOrTrialPacket.cs
AAEmu.Game/Core/Packets/G2C/SCChangeJuryOKCountPacket.cs
AAEmu.Game/Core/Packets/G2C/SCChangeJuryVerdictCountPacket.cs
AAEmu.Game/Core/Packets/G2C/SCChangeTrialStatePacket.cs
AAEmu.Game/Core/Packets/G2C/SCInviteJuryPacket.cs
AAEmu.Game/Core/Packets/G2C/SCJuryBeSeatedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCJuryWaitStatusPacket.cs
AAEmu.Game/Core/Packets/G2C/SCJuryWaitingNumberPacket.cs
AAEmu.Game/Core/Packets/G2C/SCSummonJuryPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTrialAudienceJoinedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTrialAudienceLeftPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTrialCancledPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTrialInfoPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTrialWaitStatusPacket.cs

Adding the Jury and Trial packets and structs, also updated HoustTaxPacket opcode

Added Jury and trial packets

---

AAEmu.Game/Core/Packets/C2G/CSAddBlockedUserPacket.cs
AAEmu.Game/Core/Packets/C2G/CSDeleteBlockedUserPacket.cs
AAEmu.Game/Core/Packets/C2G/CSSelectCharacterPacket.cs
AAEmu.Game/Core/Packets/G2C/SCBlockedUsersPacket.cs
AAEmu.Game/Models/Game/Blocked.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterBlocked.cs
SQL/aaemu_game.sql

Updated blocking / unblocking users
(sorry for new pull)!

Client 12 r208022 Updated blocking / unblocking users

---

AAEmu.Game/Core/Packets/G2C/SCOffsets.cs

Client 12 r208022

---

AAEmu.Game/Core/Network/Game/GameNetwork.cs
AAEmu.Game/Core/Packets/C2G/CSRankCharacterPacket.cs
AAEmu.Game/Core/Packets/C2G/CSRequestSecondPasswordKeyTablesPacket.cs
AAEmu.Game/Core/Packets/C2G/CSSetupSecondPassword.cs

Adding some CS missing packets

Missing Packets

---

AAEmu.Game/Core/Managers/UnitManagers/NpcManager.cs
AAEmu.Game/Core/Packets/C2G/CSChangeTargetPacket.cs
AAEmu.Game/Models/Game/NPChar/NpcSpawner.cs
AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
AAEmu.Game/Models/Game/Units/Combat.cs
AAEmu.Game/Models/Game/Units/Patrol.cs
AAEmu.Game/Models/Game/Units/Route/Circular.cs
AAEmu.Game/Models/Game/Units/Route/Line.cs
AAEmu.Game/Models/Game/Units/Route/Square.cs
AAEmu.Game/Models/Game/Units/Route/Track.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Models/Game/World/Spawner.cs
AAEmu.Game/Models/Tasks/UnitMove/UnitMove.cs

**If the submitted code destroys the integrity of the existing structure, or if the file is not properly classified to the designated planning location, it can be removed or redone. If there is anything wrong, please guide me to do the right work.**
Update log
```
April 19, 2019
Optimizing cruise mode
Remove redundant parameter Unit
Modifying parameters between multiple NPCs to static variables leads to shared problems
Fixed single NPC multiple trigger cruise mode problem
Optimizing Attacked Target Selection by NPC Only
April 20, 2019
Optimize NPC resurrection (15s) and corpse disappearance (20s)
Repairing the problem of body movement after NPC death
April 20, 2019
Optimizing Tracking Moving Nonlinear Migration Problem
Increasing Fixed-point Moving Route of Linear Target
Optimizing cruise …
```

Increase NPC's Passive Trigger Mobility and Attack Function

---

AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
AAEmu.Game/Models/Game/Units/Patrol.cs
AAEmu.Game/Models/Game/Units/Unit.cs

Optimizing the problem of non-return to combat state after withdrawal from combat state
Fix code merge 69# error

Optimizing the problem of non-return to combat state after withdrawal from combat state

---

AAEmu.Game/Models/Tasks/UnitMove/UnitMove.cs
AAEmu.Game/Models/Tasks/UnitPointsRegenTask.cs

Repair of HP recovery after NPC death
Repair the problem of automatic attack after NPC death

Repair of HP recovery after NPC death Repair the problem of automatic attack after NPC death

---

AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Network/Connections/GameConnection.cs
AAEmu.Game/Models/Game/Char/Character.cs
SQL/aaemu_game.sql
SQL/updates/2019-09-07_aaemu_game.sql

Added code to set the deleted flag in the characters table.
This will not actually delete the character, but will prevent it from showing up.
Possibly needs more updates on other queries like friendslists, guilds, housing, ect.

[Game] -add: marking deleted characters as deleted

---

AAEmu.Game/Core/Packets/G2C/SCNoticeMessagePacket.cs
AAEmu.Game/Scripts/Commands/Announce.cs

Updated SCNoticeMessagePacket.cs 
packet struct is complete.
Created Announce.cs in AAEmu.Game/Scripts/Commands/

Added GM Server Notifaction Functionality

---

AAEmu.Game/Core/Packets/C2G/CSStartSkillPacket.cs
AAEmu.Game/Models/Game/Char/CharacterQuests.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActCheckTimer.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActConAutoComplete.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjItemUse.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplyItem.cs
AAEmu.Game/Models/Game/Quests/Quest.cs

various bug fixes, that hopefully improve quest progression through quest steps,

[Game] -fix: Quest fixes

---

AAEmu.Game/Core/Packets/C2G/CSCreateDoodadPacket.cs
AAEmu.Game/Core/Packets/G2C/SCDoodadRemovedPacket.cs
AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncFakeUse.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncFinal.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncLootPack.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncUse.cs
AAEmu.Game/Models/Game/World/Region.cs
AAEmu.Game/Scripts/Commands/Spawn.cs
AAEmu.Game/Utils/MathUtil.cs

1. added /spawn remove xxxx to remove doodads
2.improved DoodadFuncFakeUse to better the flow of doodads for phase funcs
3. improved DoodadFuncUse for better flow od doodad funcs
4.  doodad crops now completly removed from world when harvested
5.doodad lootpacks now give items when crop harvested WIP all loot given
6. can now remove doodads from world properly
7. /spawn command improved for doodad and npc rotation
8. added additional functions to math util for doodads

Doodad placement and removal fixes, harvesting fixes, 

---

AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Core/Packets/C2G/CSNotifyInGameCompletedPacket.cs
AAEmu.Game/Core/Packets/C2G/CSRollDicePacket.cs
AAEmu.Game/Scripts/Commands/Snow.cs

Snow system allows snow to be enabled/disabled via script /snow <true/false>
script sends all online players the snow packet so online players do not need to relog
script writes the valid user input into WorldManager.Instance.IsSnowing
script announces to server that Snow was Enabled/Disabled
created a public bool "IsSnowing" in WorldManager
created method OnPlayerJoin() in WorldManager
created method Snow() in WorldManager
created a call to WorldManager.OnplayerJoin() in CSNotifyInGameCompletedPacket.cs
Created script Snow.cs

Snow System(Proper) & Client /Roll system

---

AAEmu.Game/Models/Game/Quests/Quest.cs
AAEmu.Game/Models/Game/Quests/Templates/QuestTemplate.cs
AAEmu.Game/Models/Game/World/Interactions/Use.cs

1. quest progression updates for quest items given when starting a quest
2. use.cs updated thanks nolbp
quest.cs updated Start/update routines to accommodate multiple components of the same kind, specifically kind 4(quest objectives)

Quest updates, doodad function update

---

AAEmu.Game/Configurations.json
AAEmu.Game/Core/Managers/ConfigurationManager.cs
AAEmu.Game/Data/Configurations.json
AAEmu.Game/GameService.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Configurations.cs

The ConfigurationManager lets you write configurable parameters in a JSON file to let you configure the server parameters. Right now it only controls the XP Multiplier in case you want to increase your server's XP rate.

ConfigurationManager class

---

AAEmu.Game/Core/Managers/AuctionManager.cs
AAEmu.Game/Core/Packets/C2G/CSBidAuctionPacket.cs
AAEmu.Game/Core/Packets/C2G/CSCancelAuctionPacket.cs
AAEmu.Game/Core/Packets/G2C/SCAuctionCanceledPacket.cs

- Client knows what listings you own now. 
- Client can now cancel listings.

More AH Fixes. 

---

AAEmu.Login/Core/Controllers/LoginController.cs
AAEmu.Login/ExampleConfig.json
AAEmu.Login/Models/AppConfiguration.cs

When user performs a valid login process with an invalid username an account is created with said username and password provided. User is then loged in.

Invalid username creates account and logs in

---

.gitignore
AAEmu.Game/AccessLevels.json
AAEmu.Game/Core/Packets/G2C/SCRawPacket.cs
AAEmu.Game/Scripts/Commands/SendPacket.cs
README.md
SQL/aaemu_game.sql
SQL/aaemu_login.sql
docker-compose.yaml

Dockerised db to make new developer on-boarding easier
Added /packet command that sends either the typed out packet or the file contents of a valid file path relative to AAEmu.Game
Fixed README.md title as image appears to no longer exist

QoL changes (New developer on-boarding, sending packets to client)

---

AAEmu.Game/Core/Managers/ExpeditionManager.cs
AAEmu.Game/Core/Managers/HousingManager.cs
AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Managers/MailManager.cs
AAEmu.Game/Core/Managers/SaveManager.cs
AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Core/Network/Connections/GameConnection.cs
AAEmu.Game/Data/Configurations.json
AAEmu.Game/GameService.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Housing/House.cs
AAEmu.Game/Models/Game/Items/Item.cs
AAEmu.Game/Models/Tasks/LeaveWorldTask.cs
AAEmu.Game/Models/Tasks/SaveTask/SaveTickStartTask.cs
AAEmu.Game/Scripts/Commands/Scripts.cs

- Added automatic timed saving.
- Optimized Item to have a IsDirty field to optimize item saving.
- Moved all saving into a single transaction.
- Update House properties to have a IsDirty property handle saving optimization.
- Removed the manual saves from ExpeditionManager
- Reinstated the Save when a character leaves a world as otherwise you'd lose progress since the last auto-save.
- Now using the "AutoSaveInterval" entry of Configurations.json to use as a timing for auto-saving.
- Added save to /scripts to manually trigger the database saving. This might be useful at some point.
- Probably some more stuff I forgot to mention

[Game] update: SaveManager

---

AAEmu.Game/Core/Managers/UnitManagers/NpcManager.cs
AAEmu.Game/Core/Packets/G2C/SCUnitStatePacket.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs
AAEmu.Game/Models/Game/NPChar/Npc.cs
AAEmu.Game/Models/Game/Units/Transfer.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Scripts/Commands/ShowInventory.cs

Moved Character.Inventory.Equipment all the way up to Unit.Equipment and remove the old Unit.Equip (aka. containered Unit.Equip)
Also fixed a potential bug related to ModelParams, where data could be added twice where it wasn't required.

[Game] update: Unit Equipment

---

AAEmu.Game/Core/Packets/C2G/CSConvertItemLookPacket.cs
AAEmu.Game/Core/Packets/C2G/CSCreateDoodadPacket.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncPurchase.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplyItem.cs
AAEmu.Game/Models/Game/Quests/Quest.cs
AAEmu.Game/Models/Game/Skills/Effects/GainLootPackItemEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/ReceiveLuluLeaflet.cs

Added/Moved triggers for OnAcquiredItem and OnConsumedItem to Character.Inventory.
Added a ConsumeItem at Inventory-level that can be used to consume from multiple sources (used so quest items in warehouse are also consumed)
Fix Backpack now properly equipping for a QuestActSupplyItem

[Game] fix: Item Triggers

---

AAEmu.Game/Core/Managers/AuctionManager.cs
AAEmu.Game/Core/Packets/C2G/CSBidAuctionPacket.cs
AAEmu.Game/Core/Packets/G2C/SCAuctionSearchedPacket.cs
AAEmu.Game/Models/Game/Auction/AuctionItem.cs
SQL/aaemu_game.sql
SQL/updates/2020-05-25_aaemu_game_auction_house.sql

Added locks to auction item lists. 
Fixed timers not working properly. 
Added EndTime to better track when auctions should be over. 
Added db table changes.

More ah fixes/improvements. 

---

AAEmu.Game/Core/Managers/UnitManagers/DoodadManager.cs
AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncClout.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncGrowth.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRatioChange.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncTimer.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncUse.cs
AAEmu.Game/Models/Game/World/Interactions/Butcher.cs
AAEmu.Game/Models/Game/World/Interactions/FruitPick.cs
AAEmu.Game/Models/Game/World/Interactions/SkinOff.cs
AAEmu.Game/Scripts/Commands/TickDoodad.cs

Global plants, trees & animals now grow
Added support for Butchering, Picking fruit (off trees), Shearing animals.
Added logic for doodads that transform like tree -> thunderstruck or healthy animals to become sick or hungry

Feat husbandry

---

AAEmu.Game/Models/Game/Features/Feature.cs
AAEmu.Game/Models/Game/Features/FeatureSet.cs

Disabled Dwarf/Warborns. Fixed Enum for 0.5 revision

Small FeatureSet Fix/Update

---

AAEmu.Game/Data/slave_attach_points.json

Modified script https://github.com/NickMesser/AAEmuTools/blob/master/ConvertDumpToJson/app.py to provide z rotations for certain rotation matrices.

Updated ship slave attach point rotations

---

AAEmu.Game/Scripts/Commands/AddItem.cs

Somehow the wrong namespace made it into here.

[GM] fix: wrong using statement in AddItem

---

AAEmu.Game/Models/Game/Char/CharacterMails.cs
AAEmu.Tests/MailTests.cs

added a check for money balance when sending gold
added a check for sending to confirm exists
added method to remove gold when sending.
added unit tests for two cases above.
Fixes #174

Mail gold dupe #174

---

AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Data/CharTemplates.json
AAEmu.Game/Models/Game/Char/Templates/CharacterTemplate.cs
AAEmu.Game/Models/Game/Char/Templates/CharacterTemplateConfig.cs

Startzonefix

---

AAEmu.Game/Models/Game/Quests/Quest.cs
AAEmu.Game/Scripts/Commands/Nloc.cs
AAEmu.Game/Scripts/Commands/Position.cs
AAEmu.Game/Scripts/Commands/Rotate.cs

Nloc command lets you change npc position 
updated position to work with target
updated rotate to work with optional value

Npc position command and update to other - Adds a nullcheck to quests to avoid no next step (thanks thadude!)

---

AAEmu.Game/Core/Packets/C2G/CSStartSkillPacket.cs
AAEmu.Game/Models/Game/Char/CharacterQuests.cs
AAEmu.Game/Models/Game/DoodadObj/DoodadFunc.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncFakeUse.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjMonsterGroupHunt.cs
AAEmu.Game/Models/Game/Quests/Quest.cs
AAEmu.Game/Models/Game/Skills/Effects/CraftEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/InteractionEffect.cs
AAEmu.Game/Models/Game/World/Interactions/Use.cs

A Precious Gift - Can't loot doll from tree.
The Golden Mark - After using the item can't complete quest.
various interactions didn't work
some quests didn't complete.
tried to fix most of the first 10 quests

Fixes #176

---

AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRecoverItem.cs
AAEmu.Game/Models/Game/Skills/Effects/PutDownBackpackEffect.cs
AAEmu.Game/Models/Game/World/Interactions/RecoverItem.cs

Allows you to pickup a placed pack
places pack in front of you and in the direction your facing and always facing north

Various pack fixes

---

AAEmu.Game/Core/Managers/AuctionManager.cs

Fixed issue with being able to cancel an auction if already bid on. 

---

AAEmu.Game/Models/Game/Char/CharacterMails.cs

Collecting money from a sold auction now requires and consumes 1 labor in commerce as intended.

[Mail] Auction Labor

---

AAEmu.Game/Core/Packets/C2G/CSNotifyInGamePacket.cs
AAEmu.Game/Models/Game/Char/CharacterEquipment.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffect.cs
StartGameServer.bat
StartLoginServer.bat

Fixes null in SpecialEffect.
Adds/removes a buff based on item equipped. 
Updated Bat files.

Misc Changes

---

AAEmu.Game/Core/Managers/SkillManager.cs
AAEmu.Game/Models/Game/Skills/Effects/GainLootPackItemEffect.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Skills/SkillProduct.cs

Removed the item removal from LootPackEffect. (should not have been in there)
Added checks to remove reagents from inventory skills. 
Added checks to add items from skill products. 
Fixed bug with LootPackEffect giving gold when it wasn't supposed to.

Fixed Inventory Skills

---

AAEmu.Game/Core/Managers/AuctionManager.cs

Last push. Fixed some compilers issues I didnt see the first time.

Fixed my errors

---

AAEmu.Commons/Utils/Helpers.cs
AAEmu.Game/Core/Managers/AuctionManager.cs
AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Packets/C2G/CSAuctionSearchPacket.cs
AAEmu.Game/Core/Packets/G2C/SCAuctionSearchedPacket.cs
AAEmu.Game/Models/Game/Auction/AuctionItem.cs
AAEmu.Game/Scripts/Commands/TestAuctionHouse.cs
SQL/aaemu_game.sql
SQL/updates/2020-12_04_aaemu_game_auction_house.sql

Improved AH to not save item names, timeleft, or any of the categories in the database. 
Auction Items have an IsDirty tag so they only save when needed. 
Fixed reader.DateTime issue. Was going over the Min/Max of datetime.

Ah Update, Fixed Mail, Item Names

---

AAEmu.Game/Core/Managers/MailManager.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs
SQL/updates/2020-12-10_aaemu_game_housing.sql

Implemented preferredItem functionality in ItemContainer.ConsumeItem()
Removed the old AddItem and RemoveItem in Inventory

[Items] Implemented preferredItem

---

AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterAbilities.cs

Fixed the bug where any form of exp gain would level you instantly to max level.

[EXP] Bug-fix for insta Level 55

---

AAEmu.Game/Core/Managers/World/ZoneManager.cs
AAEmu.Game/Core/Packets/C2G/CSSelectCharacterPacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Units/Buffs.cs
AAEmu.Game/Models/Game/World/Zones/ZoneGroup.cs

Added Zone Buff effect handling

[Zone] ZoneBuffs

---

AAEmu.Game/Core/Managers/TickManager.cs
AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs
AAEmu.Game/GameService.cs
AAEmu.Game/Genesis/DiscordBotService.cs

Added and updated code to allow the game server to close correctly again without error when pressing Ctrl + C

[Game] Code cleanup

---

AAEmu.Game/Models/Json/JsonDoodadSpawns.cs
AAEmu.Game/Scripts/Commands/Around.cs
AAEmu.Game/Scripts/Commands/Dloc.cs
AAEmu.Game/Scripts/Commands/Nwrite.cs

How to use!
/around doodad radius
Will display objId and its current position!
/dloc objid x y z
this command will move the doodad to the coordinates!
x y z will use current location so you can edit height quickly
/dloc objid x y 200 for example!
/rotate doodad objid rotation
rotates the doodad given the value
/nwrite doodad objid will save your changes to existing doodads or if you spawned a new doodad using /spawn doodad doodad id will save it to json as a new entry!

Add's doodad editing commands 

---

AAEmu.Game/Data/Worlds/instance_hadir_farm/doodad_spawns.json
AAEmu.Game/Data/Worlds/instance_hadir_farm/npc_spawns.json

Added priestess Nui to Hadir's farm, fix coordinate Z 
Memory Tome , added mobs and  exit portal.

1 new commit

---

AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Data/CharTemplates.json
AAEmu.Game/Scripts/Commands/Teleport.cs
SQL/updates/2021-07-21_aaemu_game_transform.sql

- Updated the rotations for newly created characters.
- Added code so this can be defined in degrees in CharTemplates.json
- Updated /teleport Lilyut to actually send you to Lilyut instead of Solzreed
- Added the missing DROP fields to the previously create 2021-07-21_aaemu_game_transform.sql

[Game] New character spawn update

---

AAEmu.Game/Core/Packets/C2G/CSSelectCharacterPacket.cs
AAEmu.Game/Models/StaticValues/BuffsEnum.cs

Added the "Logged On" buff to characters that are logging on.

[Game] Logging On

---

AAEmu.Game/Core/Managers/World/ZoneManager.cs
AAEmu.Game/Models/Game/Portal.cs

Fixes portal book cursor location when clicking on the icon to show it on the map

[Game] Portal book cursor

---

SQL/aaemu_game.sql

- Fixed the forgotten semicolon when creating the "music" table in database

 [SQL] Fix typo in SQL-Setup

---

SQL/aaemu_game.sql
SQL/updates/2021-11-12_aaemu_game_index_fix.sql

Updating some of the table indexes to help prevent database corruption

[SQL] Fix indexes

---

AAEmu.Game/Models/Game/Quests/Acts/QuestActObjAliase.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjCinema.cs

Feat quest

---

AAEmu.Game/AAEmu.Game.csproj
AAEmu.Game/Configurations/CharacterDeleteSettings.json
AAEmu.Game/Core/Managers/ExpeditionManager.cs
AAEmu.Game/Core/Managers/HousingManager.cs
AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Network/Connections/GameConnection.cs
AAEmu.Game/Core/Network/Connections/GameConnectionTable.cs
AAEmu.Game/Core/Packets/C2G/CSCancelCharacterDeletePacket.cs
AAEmu.Game/Core/Packets/C2G/CSDeleteCharacterPacket.cs
AAEmu.Game/Core/Packets/C2G/CSLeaveExpeditionPacket.cs
AAEmu.Game/Core/Packets/C2G/CSListCharacterPacket.cs
AAEmu.Game/Core/Packets/G2C/SCCharacterDeletedPacket.cs
AAEmu.Game/GameService.cs
AAEmu.Game/Models/AppConfiguration.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Configurations.cs
AAEmu.Game/Models/Game/Mails/BaseMail.cs
AAEmu.Game/Models/Game/World/Region.cs
AAEmu.Game/Models/Tasks/Characters/CharacterDeleteTask.cs
global.json

Updated the way characters get deleted, it will now properly reload character list when you're still in the character select screen.
Also changed it so it's triggered by a delayed Task rather than when requesting the character list.
Added options to configure delete delays and if the name should be freed up or not

[Game] Character Delete

---

AAEmu.Game/Core/Packets/C2G/CSBuyItemsPacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterActability.cs
AAEmu.Game/Models/Game/DoodadObj/Templates/DoodadTemplate.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/GiveHonorPoint.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/GiveLivingPoint.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Models/StaticValues/GamePointKind.cs
AAEmu.Game/Models/Tasks/Characters/CharacterDeleteTask.cs

Groundwork for earning vocation badges from doing vocation interactions with doodads.
Added ChangeGamePoints function to Character to handle Honor and Vocation.
Added GamePointsKind enum
Implemented SpecialEffectAction GiveLivingPoint

[Game] Earn Vocation Badges

---

AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Network/Game/GameNetwork.cs
AAEmu.Game/Core/Packets/C2G/CSApplyBeautySalonPacket.cs
AAEmu.Game/Core/Packets/C2G/CSBeautyshopDataPacket.cs
AAEmu.Game/Core/Packets/C2G/CSEnterBeautySalonPacket.cs
AAEmu.Game/Core/Packets/C2G/CSExitBeautySalonPacket.cs
AAEmu.Game/Core/Packets/C2G/CSOffsets.cs
AAEmu.Game/Core/Packets/G2C/SCCharacterGenderAndModelModifiedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCToggleBeautyshopResponsePacket.cs
AAEmu.Game/Models/Game/Items/Item.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs
AAEmu.Game/Models/Game/Skills/BuffConstants.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/EnterBeautyshop.cs

Implemented Beauty Salon functionality

[Game] Beauty Salon

---

AAEmu.Game/Data/Portal/return_points.json

Added  Memory Tome points in the Arcum Iris,Tigerspine Mountains,Mahadevi

Added  Memory Tome points on the Haranya continent

---

AAEmu.Game/Data/Portal/return_points.json

Added Memory Tome point and name correction

[Data] WIP: Added Memory Tome point and name correction

---

AAEmu.Game/Data/Portal/return_points.json

fixed portals in Ynystere and Marianople, added Memory Tome in Auroria continent

[Data] Added missing Memory Tome

---

AAEmu.Game/Data/Portal/return_points.json

[Data] Added Memory Tome points Haranya continent in Windscour Savannah.

[Data] Added Memory Tome points  Haranya continent;

---

AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Data/Worlds/world_spawns.json
AAEmu.Game/Models/Game/World/World.cs
AAEmu.Game/Models/Game/World/WorldSpawnLocation.cs

Fix for the missing spawn locations for instances that was introduced when moving to ClientData.
Created a new json for the missing data until we can find a better fix.

[Game] Bugfix: Instance spawn locations

---

AAEmu.Game/Data/Portal/return_points.json

[Data] Added Memory Tome points Haranya and Auroria continents;

[Data] Added Memory Tome points Haranya and Auroria continents ;

---

AAEmu.Game/Data/Portal/return_points.json

[Data] Added Memory Tome points Haranya continent and correct points.

[Data] Added Memory Tome points Haranya  continent ;

---

AAEmu.Game/Data/Portal/return_points.json

[Data] Added Memory Tome points Haranya continent and correct names.

[Data] Added Memory Tome points Haranya continent ;

---

AAEmu.Game/Data/Portal/return_points.json

[Data] Added Glitterstone Memory Tome.

[Data] Added Memory Tome points Haranya continent;

---

AAEmu.Game/Core/Managers/HousingManager.cs

[Game] Fix: WorldId when building a house

---

AAEmu.Game/Models/Game/Char/Character.cs

Co-authored-by: ZeromusXYZ
Co-authored-by: Gene

Fix grant xp if consuming labor

---

AAEmu.Commons/Utils/RandomElementByWeight.cs
AAEmu.Game/Core/Managers/HousingManager.cs
AAEmu.Game/Core/Managers/TransferTelescopeManager.cs
AAEmu.Game/Core/Managers/World/StreamManager.cs
AAEmu.Game/Core/Network/Connections/GameConnection.cs
AAEmu.Game/Core/Packets/G2C/SCAttachmentTakenPacket.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/AlmightyAttackBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/ReturnStateBehavior.cs

Applying coding suggestions from SonarCloud Quality Gate

Code Cleaning

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Models/Game/Char/CharacterCraft.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Crafts/Craft.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs

[Game] Possible fix for crafting and missing Items

---

AAEmu.Game/Core/Managers/Id/ContainerIdManager.cs
AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Managers/MusicManager.cs
AAEmu.Game/Core/Managers/SaveManager.cs
AAEmu.Game/Core/Network/Connections/GameConnection.cs
AAEmu.Game/Core/Packets/G2C/SCUnitStatePacket.cs
AAEmu.Game/Core/Packets/L2G/LGRegisterGameServerPacket.cs
AAEmu.Game/GameService.cs
AAEmu.Game/Models/ClientData/Hmap.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterEquipment.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Items/Containers/CofferContainer.cs
AAEmu.Game/Models/Game/Items/Containers/EquipmentContainer.cs
AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs
AAEmu.Game/Models/Game/Items/Item.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Tests/InventoryTests.cs
AAEmu.sln.DotSettings
AAEmu.sln.DotSettings.user
SQL/aaemu_game.sql
SQL/updates/2022-05-14_aaemu_game_item_containers.sql

Preparations for making housing coffers and other persistent ItemContainers.
It's written in such a way that it will auto-generate new containers for already existing items.
Make sure the MySQL is updated first before running the new code.
The point is to make it so we don't really have a limit on owned Coffers with at the same time not having to split Item objects into multiple tables. (container_id added to items DB for this)

[Game] Persistent ItemContainers

---

AAEmu.Commons/Utils/Updater/MySqlDatabaseUpdater.cs
AAEmu.Game/GameService.cs
AAEmu.Login/Core/Network/Login/LoginNetwork.cs
AAEmu.Login/LoginService.cs
SQL/updates/readme.txt

Added code to automatically run SQL updates as required.
Please check the readme.txt in the SQL\Updates folder for more info.

[Common] Auto SQL updater

---

AAEmu.Game/Data/Portal/worldgates.json

Added missing portals to Mistral Hall to access instances

Develop feat npc spawner&game schedulefx

---

AAEmu.Game/AAEmu.Game.csproj
AAEmu.Game/Core/Packets/C2G/CSSendChatMessagePacket.cs
AAEmu.Game/Scripts/Commands/ItemCmd.cs
AAEmu.Game/Utils/Converters/ChatConverter.cs
AAEmu.Game/Utils/Scripts/SubCommands/Item/ItemAddSubCommand.cs

- Added a new message serializer for item template references
- Added new SubCommand for Item Add. (Used to test the messages)

Add item message reference and Add item Subcommand

---

AAEmu.Game/Core/Packets/C2G/CSChangeTargetPacket.cs
AAEmu.Game/Models/Game/Char/CharacterCraft.cs
AAEmu.Game/Models/Game/Char/CharacterQuests.cs
AAEmu.Game/Models/Game/Quests/Quest.cs

- Fixed quest ID=6024, "Hereafter Stones", 10, "Lilyut Hills", "Lilyut Hills";

[Game] WIP: Quest bug fixes:

---

AAEmu.Game/Program.cs
AAEmu.Game/Scripts/Commands/Damage.cs
AAEmu.Login/Program.cs

Updated damage command to allow damaging targets instead of only self.
Added handling of damage value if % is added directly behind the number.
Also added a new error message if the server could not load a valid MySQL configuration.

[Game] Updated damage command

---

AAEmu.Game/Scripts/Commands/Help.cs

Forgot to adjust the help script for the new AccessLevelManager

[Game] Fix: Help

---

SQL/updates/2022-07-07_aaemu_login_example-server.sql
SQL/updates/2022-07-07_aaemu_login_test-user.sql

These seem to have been added at some point, but have no place inside updates, and should remain in the examples folder.

[MySQL] Removed example data in updates

---

AAEmu.Game/Core/Managers/MailManager.cs
AAEmu.Game/Core/Packets/G2C/SCQuestRewardedByMailPacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterQuests.cs
AAEmu.Game/Models/Game/Items/ItemCreationDefinition.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplyCopper.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplyExp.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplyHonorPoint.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplyItem.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplyLivingPoint.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplySelectiveItem.cs
AAEmu.Game/Models/Game/Quests/Quest.cs

Mails quest rewards (items and/or gold) to the player if their inventory is full.
Also did some other simplifications related to quest rewards.

[Game] Mail Quest Rewards

---

AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs

Boats now display their movement and turning speed correctly in the boat info window.
Incidentally, this also seems to the fix rubber-banding we had.

[Game] Boat Speed Info

---

AAEmu.Tests.Integration/AAEmu.Tests.Integration.csproj
AAEmu.Tests.Integration/ExampleConfig.json
AAEmu.Tests.Integration/readme.md

Adding instructions + Example config file for integration tests

Adding readme and exampleconfig file to Integration tests

---

AAEmu.Commons/Utils/XML/XmlHelper.cs
AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/GameService.cs
AAEmu.Game/Models/Game/World/WaterBodies.cs
AAEmu.Game/Models/Game/World/WaterBodyArea.cs
AAEmu.Game/Models/Game/World/World.cs
AAEmu.Game/Scripts/Commands/Fly.cs
AAEmu.Game/Scripts/Commands/Pirate.cs
AAEmu.Game/Scripts/Commands/WaterEdit.cs
AAEmu.Game/Utils/Scripts/ScriptCompiler.cs

Adds support to edit water body data for the boat physics to use, by initializing estimated values taken from the game client.
These still need to be edited to be useful, which I will add in later PRs

[Game] Added water editor

---

AAEmu.Game/Core/Managers/CommandManager.cs
AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Core/Packets/C2G/CSChangeTargetPacket.cs
AAEmu.Game/Core/Packets/G2C/SCCharacterReturnDistrictsPacket.cs
AAEmu.Game/Data/Portal/recalls.json
AAEmu.Game/Models/Game/Char/CharacterPortals.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncBinding.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Scripts/Commands/Pirate.cs

Fixed possible enumeration issues with slaves
Added more info to NewSubZone handling
Fixed portal book to be used without a recall being set
Changed SetFaction to allow players again

[Game] Fixes

---

SQL/aaemu_game.sql

Added missing fields for initial installation in the items table.

[SQL] Missing fields

---

AAEmu.Game/Models/Game/Char/Inventory.cs

Fixed a potential issue when trying to equip a 2-handed weapon with nothing in the offhand.

[Game] Fix: equip 2-handed

---

AAEmu.Game/Core/Managers/MailManager.cs
AAEmu.Game/Core/Network/Game/GameNetwork.cs
AAEmu.Game/Core/Packets/C2G/CSICSBuyGoodPacket.cs
AAEmu.Game/Core/Packets/C2G/CSOffsets.cs
AAEmu.Game/Core/Packets/C2G/CSTakeAllAttachmentItemPacket.cs
AAEmu.Game/Models/Game/Char/CharacterMails.cs
AAEmu.Game/Models/Game/Mails/CommercialMail.cs
AAEmu.Game/Models/Game/Mails/CountUnreadMail.cs
AAEmu.Game/Models/Game/Mails/MailType.cs

Added new CommerialMail type for use in marketplace sales.
Implemented marketplace mail, and missing CSTakeAllAttachmentsItemPacket.
Enabled marketplace gifting.

[Game] Added mails for InGame Cash Shop

---

AAEmu.Game/Core/Packets/C2G/CSStartInteractionPacket.cs
AAEmu.Game/Models/StaticValues/SkillsEnum.cs

Giddy up you can now right click instead of pressing 'g'

Adds right click mounting to horsies

---

AAEmu.Game/Core/Managers/TaskManager.cs
AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/DoodadObj/DoodadSpawner.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncPulse.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncPulseTrigger.cs
AAEmu.Game/Models/Json/JsonDoodadSpawns.cs

[Game] Added  related doodads;

---

AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRecoverItem.cs

When recovering a doodad that has a item attached, it would not delete the doodad.

[Game] Fix: Recover item from doodad

---

AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Managers/World/EnterWorldManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/AttackBehavior.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterMates.cs
AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
AAEmu.Game/Models/Game/Units/Unit.cs

- moved CombatTick, RegenTick, BreathTick to Unit class;
- added a check that if a character dies on a horse, it ran away;

[Game] Fixed pet Hp regeneration:

---

AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Packets/C2G/CSUpdateActionSlotPacket.cs
AAEmu.Game/Core/Packets/G2C/SCActionSlotsPacket.cs
AAEmu.Game/Models/Game/Char/ActionSlot.cs
AAEmu.Game/Models/Game/Char/Character.cs

- updated enum ActionSlotType;
- updated SCActionSlotPacket;
- updated CSUpdateActionSlotPacket;
- added SetAction metod;
- ActionId now ulong;

[Game] Updated ActionSlot (requires to recreate the characters):

---

AAEmu.Game/Core/Managers/MateManager.cs
AAEmu.Game/Core/Managers/TransferManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Core/Packets/C2G/CSMoveUnitPacket.cs
AAEmu.Game/Core/Packets/C2G/CSUnbondDoodadPacket.cs
AAEmu.Game/Core/Packets/Proxy/FinishStatePacket.cs
AAEmu.Game/Models/Game/Char/CharacterMates.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncAttachment.cs
AAEmu.Game/Models/Game/Units/Transfer.cs
AAEmu.Game/Models/Game/World/Region.cs
AAEmu.Game/Models/Game/World/Transform/Transform.cs

[Game] Fixed Carriage/Mate disappearing when crossing zone boundaries;

---

AAEmu.Game/Core/Managers/DuelManager.cs
AAEmu.Game/Core/Packets/C2G/CSChallengeDuelPacket.cs
AAEmu.Game/Core/Packets/C2G/CSStartDuelPacket.cs
AAEmu.Game/Core/Packets/G2C/SCDuelEndedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCDuelStartedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCDuelStatePacket.cs
AAEmu.Game/GameService.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Duels/Duel.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Models/Tasks/Duels/DuelDistanceСheckTask.cs
AAEmu.Game/Models/Tasks/Duels/DuelEndTimerTask.cs
AAEmu.Game/Models/Tasks/Duels/DuelFuncTask.cs
AAEmu.Game/Models/Tasks/Duels/DuelResultСheckTask.cs
AAEmu.Game/Models/Tasks/Duels/DuelStartTask.cs

[Game] Added the ability to challenge to a duel:

---

AAEmu.Game/Core/Managers/DuelManager.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Models/Tasks/Duels/DuelResultСheckTask.cs

- we don't let you die during a duel (hp=1);

[Game] Fixed Duel:

---

AAEmu.Game/Models/Game/AI/v2/Params/AiSkillList.cs

[Game} WIP: Updated the ParseLua method:

---

AAEmu.Game/Core/Managers/World/EnterWorldManager.cs
AAEmu.Game/Core/Network/Connections/GameConnection.cs
AAEmu.Game/Core/Packets/C2G/CSCancelLeaveWorldPacket.cs

- We refuse to use TaskManager / Quartz;

[Game] Fixed hanging when exiting the game:

---

SQL/aaemu_game.sql

Added Archeum Lodestone in Auroria

[SQL] Added Archeum Lodestone

---

AAEmu.Game/Core/Managers/SaveManager.cs
AAEmu.Game/Models/Game/Char/ICharacter.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Scripts/Commands/WorldCmd.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetAutosaveintervalSubCommand.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetExprateSubCommand.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetGrowthrateSubCommand.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetHonorrateSubCommand.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetLogoutmessageSubCommand.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetLootrateSubCommand.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetMotdmessageSubCommand.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetSubCommand.cs
AAEmu.Game/Utils/Scripts/SubCommands/World/WorldSetVocationrateSubCommand.cs

- /world set [growthrate|lootrate|vocationrate|honorrate|exprate|autosaveinterval|logoutmessage|motd]

[Scripts] Added command to change world parameters:

---

AAEmu.Commons/Network/PacketBase.cs
AAEmu.Commons/Network/PacketLogLevel.cs
AAEmu.Game/Core/Network/Game/GamePacket.cs
AAEmu.Game/Core/Network/Stream/StreamPacket.cs
AAEmu.Game/Core/Packets/C2S/CTCancelCellPacket.cs
AAEmu.Game/Core/Packets/C2S/CTContinuePacket.cs
AAEmu.Game/Core/Packets/C2S/CTRequestCellPacket.cs
AAEmu.Game/Core/Packets/G2C/SCGimmickMovementPacket.cs
AAEmu.Game/Core/Packets/G2C/SCOneUnitMovementPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTargetChangedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCTransferTelescopeUnitsPacket.cs
AAEmu.Game/Core/Packets/G2C/SCUnitMovementsPacket.cs
AAEmu.Game/Core/Packets/Proxy/FastPingPacket.cs
AAEmu.Game/Core/Packets/Proxy/FastPongPacket.cs
AAEmu.Game/Core/Packets/Proxy/PingPacket.cs
AAEmu.Game/Core/Packets/Proxy/PongPacket.cs
AAEmu.Game/Core/Packets/S2C/TCDoodadIdsPacket.cs
AAEmu.Game/Core/Packets/S2C/TCDoodadStreamPacket.cs

Added ``LogLevel`` property to ``BasePacket`` which can be override to change the wanted Nlog level when the packet get sent or received.
Default ``LogLevel`` is ``PacketLogLevel.Debug``

[Game] Custom packet log levels

---

AAEmu.Game/Scripts/Commands/AddBadges.cs

Added a command to add Vocation Badges to buy items

[Scripts] Added command to add Vocation Badges

---

AAEmu.Game/Core/Packets/C2G/CSBuyItemsPacket.cs

Co-author ZeromusXYZ.
Fixed the calculation of spending. Correctly spent honor points and vocation badges,  instead of being added when purchasing items, they are now spent.

[Packets] fixed CSBuyItemsPacket:

---

AAEmu.Game/Core/Packets/C2G/CSInteractNPCEndPacket.cs
AAEmu.Game/Core/Packets/C2G/CSInteractNPCPacket.cs
AAEmu.Game/Core/Packets/C2G/CSRepairAllEquipmentsPacket.cs
AAEmu.Game/Core/Packets/C2G/CSRepairSingleEquipmentPacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Units/Unit.cs

Allows you to repair items so long as you are interacting with and near a blacksmith.
**Known issue:** `MaxDurability` is returning the wrong value, so items will end up with slightly more or slightly less than their max durability. I'm not sure why yet.

[Game] Item repair implementation

---

AAEmu.Game/Core/Managers/AuctionManager.cs
AAEmu.Game/Core/Managers/NameManager.cs

Added a fix that should fix the issue when sending cancellation mails when a player places a new bid.
Added another check to be extra sure.
This should fix issue #640

[Game] Fix: Auction Cancel Mail

---

AAEmu.Game/Core/Managers/MateManager.cs
AAEmu.Game/Core/Packets/C2G/CSStartSkillPacket.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/BaseCombatBehavior.cs
AAEmu.Game/Models/Game/Mate/MountAttachedSkills.cs
AAEmu.Game/Models/Game/Mate/MountSkills.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Skills/SkillCaster.cs

- added reading of mount_skills and mount_attached_skills tables;
- in SkillCasterType replaced Unk3 with Mount;
- in CSStartSkillPacket added a check for skill casting by a pet and added skill casting by a character sitting on a pet;

[Game] Fix pet skills:

---

AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Skills/Utils/SkillTargetingUtil.cs
AAEmu.Game/Models/Game/Team/Team.cs

Fixed SongCraft buffs when interacting with mounts

[Game] Fixed SongCraft buffs

---

AAEmu.Game/Models/Game/Items/Accessory.cs
AAEmu.Game/Models/Game/Items/Armor.cs

Now the items are being repaired correctly

[Game] Fixed durability formula

---

AAEmu.Game/Core/Managers/UnitManagers/DoodadManager.cs

Fixed the display on the scarecrow for animals and some plants that have an interface like decorative items

[Game] Fixed planting

---

AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs
AAEmu.Game/Models/Game/Units/Slave.cs
AAEmu.Game/Models/Game/Units/Unit.cs

- Added a check for collision with shore and subsequent ship damage if continuing to collide with shore;
- added locking in the loop on ships in the PhysicsThread method;

[Game] For BoatPhysicsManager:

---

AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs
AAEmu.Game/Models/Game/Units/Slave.cs

- Do not allow the ship to roll over;

[Game] boat fix:

---

AAEmu.Game/Models/Game/Mails/CommercialMail.cs

fixed sending a ' in mail title and body 
fixes #686

fix ' in mail title and body

---

AAEmu.Game/Core/Managers/World/SpawnManager.cs
AAEmu.Game/Models/Game/NPChar/NpcSpawner.cs

1. if this is the first start of the server, then only spawn - NpcSpawnerCategory.Autocreated;
2. if it's a normal Npc spawn then skip NpcSpawnerCategory.Autocreated;
3. if there are players around, we'll increase the number of Npc: suspendSpawnCount * playerCount;

[Game] Updated NpcSpawner:

---

AAEmu.Game/AAEmu.Game.csproj
AAEmu.Game/Configurations/LabowPower.json
AAEmu.Game/Core/Managers/LaborPowerManager.cs
AAEmu.Game/Models/AppConfiguration.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/ICharacter.cs
AAEmu.Game/Models/Game/Configurations.cs

Fixed labor regen, now labor power will be charged correctly when the character is offline

[Game] Fixed labor regen

---

AAEmu.Game/Scripts/Commands/Nudge.cs

Added ``/nudge`` command that just move you forward some amount (5m by default).
In combination with ``/fly`` this can be handy to get out of bounds by going through walls.

[Game] /nudge

---

AAEmu.Game/Core/Managers/UnitManagers/NpcManager.cs
AAEmu.Game/Models/Game/Char/CharacterQuests.cs
AAEmu.Game/Models/Game/NPChar/Npc.cs
AAEmu.Game/Models/Game/NPChar/NpcTemplate.cs
AAEmu.Game/Models/Game/Quests/Quest.cs

Added support for the aggro functions for quests.
You can now get quest from engaging mobs, and get the reward if you killed it (not properly added yet for raids)
Also added the doodad Golgi's Device so the Firran Main quests can be finished in Tigerspine ``Golgi's Curse ( 1572 )``

[Game] Quests: Added OnAggro support

---

AAEmu.Game/Core/Managers/AiGeodataManager.cs
AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Core/Packets/G2C/SCBuffCreatedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCBuffRemovedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCSkillEndedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCSkillFiredPacket.cs
AAEmu.Game/Core/Packets/G2C/SCUnitPointsPacket.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/BaseCombatBehavior.cs
AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/DoodadObj/DoodadSpawner.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncFinal.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRatioChange.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRatioRespawn.cs
AAEmu.Game/Models/Game/NPChar/Npc.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Units/Route/Simulation.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Scripts/Commands/Around.cs

Fixes to DoodadFuncRatioRespawn to allow adjustment of the next spawned item.
Also includes some changes to logging to reduce log spam, mostly by changing logging to Trace for some packets.

[Game] Small changes to Doodad spawning

---

.github/workflows/dotnetcore.yml
.gitignore
AAEmu.Game/AAEmu.Game.csproj
AAEmu.Game/Program.cs
AAEmu.Game/Properties/launchSettings.json
AAEmu.Game/Scripts/Commands/Nwrite.cs
AAEmu.Game/Scripts/SubCommands/Doodads/DoodadPositionSubCommand.cs
AAEmu.Game/Scripts/SubCommands/Doodads/DoodadSaveSubCommand.cs
AAEmu.Game/Scripts/SubCommands/Npcs/NpcInformationSubCommand.cs
AAEmu.Game/Scripts/SubCommands/Npcs/NpcPositionSubCommand.cs
AAEmu.Game/Scripts/SubCommands/Npcs/NpcSaveSubCommand.cs
AAEmu.Game/Scripts/SubCommands/Slaves/SlaveInformationSubCommand.cs
AAEmu.Game/Scripts/SubCommands/Slaves/SlavePositionSubCommand.cs
AAEmu.Game/Scripts/SubCommands/Slaves/SlaveSaveSubCommand.cs
AAEmu.Game/Utils/Scripts/ScriptCompiler.cs

In a way to avoid discovering in the runtime that the Compilation fails, this PR addes this check as a step on the PRs build pipeline

Add Scripts Compilation check to PR builds

---

AAEmu.Game/Data/Worlds/main_world/npc_spawns.json

Fixed z-coordinate of birds in Arcum Iris and quest npcs 3111 Gorgon, 3284 Flooded Tomb Ghost in Silent Forest.  Added missing npcs 3309 Royal Tomb Guardian in Silent Forest.  Added missing quest doodad 7046 Bloodstain.

[Data] Fixed npc and doodads

---

AAEmu.sln

Adding the additional files visibility to the solution view

Additional files update

---

AAEmu.Game/Models/Game/Items/Loots/LootPack.cs

Co-authored-by: ZeromusXYZ
Fixed loot dropping out of quest reward boxes as per description

[Game] Loot Drop

---

AAEmu.Game/Models/Game/Skills/Effects/CraftEffect.cs

Fixed a bug where some single-item crafts that use the collect method instead of craft would be unable to be collected on craft.

[Game] Fix: Single Crafts

---

AAEmu.Game/Core/Managers/HousingManager.cs
AAEmu.Game/Core/Packets/C2G/CSDecorateHousePacket.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncUse.cs
AAEmu.Game/Scripts/Commands/TestHouse.cs

Some function where referencing the houses DB Id instead of it's TlId that the client sends.

[Game] Fix housing related issue

---

AAEmu.Game/Core/Managers/HousingManager.cs

[Game] Hotfix House TlId

---

AAEmu.Game/Models/Game/Units/BaseUnit.cs

Added a null-check for the zone and zone faction.
Some were reporting 0 / null (like library parts)
Defaulted them to neutral

[Game] CanAttack added null-check

---

AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/ReturnStateBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Framework/NpcAi.cs
AAEmu.Game/Models/Game/NPChar/Npc.cs
AAEmu.Game/Models/Game/Skills/BuffConstants.cs
AAEmu.Game/Models/Game/Units/BaseUnit.cs
AAEmu.Game/Models/Game/Units/Buffs.cs
AAEmu.Game/Models/StaticValues/TagsEnum.cs

Added code to reset aggro when a player or NPC enters a safe zone. (e.g. near a Nui Statue)

[Game] Reset aggro on safe zones

---

AAEmu.Game/Models/Game/Units/BaseUnit.cs

Fixes the bug where Local mobs couldn't attack the player in their home zones.

[Game] Fix: Mob Hostility check

---

AAEmu.Game/AAEmu.Game.csproj
AAEmu.Game/Program.cs
AAEmu.Game/README.md
AAEmu.Game/Services/WebApi/Controllers/WorldController.cs
AAEmu.Game/Services/WebApi/RouteDefinition.cs
AAEmu.Game/Services/WebApi/RouteMapper.cs
AAEmu.Game/Services/WebApi/WebApiServer.cs
AAEmu.Game/Services/WebApi/WebApiSession.cs
AAEmu.UnitTests/Services/WebApi/RouteMapperTests.cs
AAEmu.UnitTests/Services/WebApi/WebApiSessionTests.cs

- To enable more smart controllers had to change the RouteMapper logic to actually be able to identify urls using Regular Expression.
This change will allow Controller methods to accept a url pattern instead of a static path.
- Removed the requirement for a `Config.json` file when using User Secrets to store configuration.
- Added missing UserSecrets properties present in Config.json in the Readme.
- Unit Tests added to ensure the regex behavior

Commands Controller - Phase 1

---

AAEmu.Game/Core/Managers/ISkillManager.cs
AAEmu.Game/Core/Managers/Id/SkillTlIdManager.cs
AAEmu.Game/Core/Managers/SkillManager.cs
AAEmu.Game/GameService.cs
AAEmu.Game/Models/Game/Skills/Plots/Tree/PlotTree.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.IntegrationTests/Models/Game/Quests/QuestTests.cs

Potential fix for Skill Tl Id issues
[Game] Fix - SkillTlId limit

[Game] Fix - SkillTlId limit

---

AAEmu.Game/Core/Managers/QuestManager.cs
AAEmu.Game/Models/Game/Char/CharacterQuests.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjItemGather.cs
AAEmu.Game/Models/Game/Quests/Quest.cs
AAEmu.Game/Models/Game/Skills/Effects/AcceptQuestEffect.cs

Added a fix to quest starting items so they will now start the correct quest.
Added code to QuestActObjGatherItem to allow the Cleanup flag to work when the quest is finished.

[Game] Fix Quests starting items and gather objective

---

AAEmu.Game/Core/Managers/Id/SkillTlIdManager.cs
AAEmu.Game/Core/Packets/C2G/CSMoveUnitPacket.cs
AAEmu.Game/Core/Packets/C2G/CSStopCastingPacket.cs
AAEmu.Game/Core/Packets/G2C/SCSkillEndedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCSkillStartedPacket.cs
AAEmu.Game/Core/Packets/G2C/SCSkillStopped.cs
AAEmu.Game/GameService.cs
AAEmu.Game/Models/Game/AI/v2/Framework/Behavior.cs
AAEmu.Game/Models/Game/Quests/Quest.cs
AAEmu.Game/Models/Game/Skills/Plots/Tree/PlotTree.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Units/Combat.cs
AAEmu.IntegrationTests/Models/Game/Quests/QuestTests.cs

- Made a custom SkillTlIdManager for more detailed information
- Also moved most quest logs to debug because reasons
- Changed some debug logs
- Changed some things in ``skills.cs`` like range checking and mana cost check.

[Game] SkillTlId fixing?

---

AAEmu.Game/Models/Game/Skills/Skill.cs

Added fix to consume one source item, if the source item is marked as UseSkillAsReagent, but no actual items are referenced as reagent.
Fixes the bug that prevented you from dropping a Portable Harpoon Canon (item 23836) before the buff had expired.

[Game] Fix issue with empty skill reagents

---

AAEmu.Game/Core/Managers/IndunManager.cs
AAEmu.Game/Core/Managers/World/SpawnManager.cs
AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Core/Packets/C2G/CSMoveUnitPacket.cs
AAEmu.Game/Data/Portal/worldgates.json
AAEmu.Game/Data/Worlds/instance_howling_abyss/npc_spawns.json
AAEmu.Game/Data/Worlds/instance_library/doodad_spawns.json
AAEmu.Game/Data/Worlds/world_spawns.json
AAEmu.Game/Models/Game/DoodadObj/DoodadSpawner.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncEnterInstance.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncEnterSysInstance.cs
AAEmu.Game/Models/Game/Indun/Dungeon.cs
AAEmu.Game/Models/Game/NPChar/NpcSpawner.cs
AAEmu.Game/Models/Game/NPChar/NpcSpawnerNpc.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/ExitArchemall.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/Return.cs
AAEmu.Game/Models/Game/Units/UnitCooldowns.cs
AAEmu.Game/Models/Game/World/WorldSpawnLocation.cs

- fixed duplication when spawning Npc;
- added Id field for instances and updated Load method in WorldManager;
- updated CheckCooldown method;
- added creation of system instances;
- [Data] WIP: fixed Npc spawning in instance_howling_abyss;

[Game] WIP: Work with dungeons:

---

AAEmu.Game/Models/Game/Char/CharacterQuests.cs

Fixes the bug where quests end up in their next step or completed after reloading the character.

[Game] Fix - Quest status not properly loading

---

AAEmu.Game/Models/Game/Quests/Acts/QuestActEtcItemObtain.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjInteraction.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjItemGather.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjItemGroupGather.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjItemGroupUse.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjItemUse.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjMonsterGroupHunt.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjMonsterHunt.cs
AAEmu.Game/Models/Game/Quests/NewQuestCode.cs

- fixed the work of quests like ID=266, "Liam's Fields", where you need to hunt and gather;
- moved status variables from QuestActObj* classes to the Quest class;

[Game] quest system fix:

---

AAEmu.Game/Models/Game/NPChar/NpcSpawnerNpc.cs

Fixes the respawn timers for NPCs.
Code was incorrectly creating a new spawner on respawns, which always had a default respawn time of 15 seconds.

[Game] Fix NPC respawn issues

---

AAEmu.Game/GameData/ItemConversionGameData.cs
AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs

Damage multipliers on DamageEffect were not correctly applied. Also made that part a bit more readable.

[Game] Fix Damage multipliers from stats

---

AAEmu.Game/Models/Game/AI/v2/Behaviors/Archer/ArcherAttackBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/BaseCombatBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/BigMonster/BigMonsterAttackBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/AttackBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/WildBoar/WildBoarAttackBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Framework/Behavior.cs

- now archers do not approach closer than long range;
- now archers run back to ranged attack distance (needMakeAGap);

[Game] AI changes:

---

AAEmu.Game/GameData/AiGameData.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/BaseCombatBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/WildBoar/WildBoarAttackBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Framework/Behavior.cs
AAEmu.Game/Models/Game/AI/v2/Params/WildBoar/WildBoarAiParams.cs
AAEmu.Game/Models/Game/AI/v2/Params/WildBoar/WildBoarAiSpurtSkill.cs

- fixed the ShouldReturn method, now Npc return to the spawn location if they move further than returnDistance or absoluteReturnDistance
- fixed WildBoarAttackBehavior, WildBoarAiParams and WildBoarAiSpurtSkill;
- fixed AiGameData;
[Game] updated CSMoveUnitPacket:
- the character does not move if he has buffs: Stun, Sleep, Root, Knockdown or Fastened;

[Game] updated AI:

---

AAEmu.Game/Models/Game/World/Transform/Transform.cs

- Previously, there was a mistake: when building a house with its rotation, the planting of crops was not in the place where they wanted to place it, but in a completely different place;

[Game] Crop placement fixes:

---

AAEmu.Game/Core/Managers/GimmickManager.cs
AAEmu.Game/Core/Managers/ModelManager.cs
AAEmu.Game/Core/Managers/SaveManager.cs
AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Core/Managers/TransferManager.cs
AAEmu.Game/Core/Managers/UnitManagers/NpcManager.cs
AAEmu.Game/Models/Game/Gimmicks/GimmickSpawner.cs
AAEmu.Game/Models/Game/Models/VehicleModel.cs
AAEmu.Game/Models/Game/Skills/Plots/PlotEventEffect.cs
AAEmu.Game/Models/Game/Skills/Plots/Tree/PlotNode.cs
AAEmu.Game/Models/Game/Skills/Templates/BuffTemplate.cs
AAEmu.Game/Models/Game/Units/Buffs.cs
AAEmu.Game/Models/Game/Units/IBuffs.cs
AAEmu.Game/Models/Game/Units/Transfer.cs
AAEmu.Game/Models/Game/World/GameObject.cs
AAEmu.Game/Models/Game/World/Region.cs
AAEmu.Game/Models/Game/World/Transform/PositionAndRotation.cs
AAEmu.Game/Program.cs
AAEmu.Game/Utils/MathUtil.cs

[Game] updated FindDifferenceBetweenRegions() method;
[Game] Fixed formatting in some files;
[Game] attempt to fix [ERROR] PlotNode - [Plot Effects Error]: Collection was modified; enumeration operation may not execute.

[Game] improving public transport;

---

AAEmu.Game/Models/Game/Quests/Quest.cs

Fixed the issue where quest rewards would be included in the quest cleanup code. Effectively removing quest rewards.

[Game] Fix quest cleanup

---

AAEmu.Game/Core/Managers/QuestManager.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActObjZoneKill.cs
AAEmu.Game/Models/Game/Quests/NewQuestCode.cs
AAEmu.Game/Models/Game/Quests/QuestState.cs
AAEmu.Game/Models/Game/Units/UnitEvents.cs

Quests that require zone-specific kills will no longer auto-complete and now correctly require the kills in those zones.
For example, arena and zone kill honor guard quests.

[Game] Added zone specific kill quest functionality

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/GameData/FishDetailsGameData.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncBuyFish.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncConvertFish.cs
AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs
AAEmu.Game/Models/Game/Items/Loots/lootPackConvertFish.cs
AAEmu.Game/Models/Game/World/Interactions/Use.cs
AAEmu.Game/Scripts/SubCommands/Items/ItemAddSubCommand.cs

- added LootPackConvertFish class;
- added _lootPackConvertFish dictionary;
- fixed GetLootConvertFish method;
- added GetLootPackIdByItemId method;

[Game] Fixed making trophies from fish:

---

AAEmu.Game/Models/Game/Skills/Effects/SpecialEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/SkillUse.cs

Updated SpecialEffect:
- added a check for the number of repetitions of the EffectRepeatCount effect;
- added delay between EffectRepeatTick effects;

[Game] there is no animation of water splashing on the tractor:

---

AAEmu.Game/Models/Game/AI/v2/Behaviors/WildBoar/WildBoarAttackBehavior.cs

- the appearance of a character next to ID=8564, Mother Seabug leads to an error in the WildBoarAttackBehavior class;

[Game] fixing an error that causes the server to shut down:

---

AAEmu.Game/Models/Game/Skills/Plots/Tree/PlotTargetInfo.cs
AAEmu.Game/Models/Game/Skills/Skill.cs

- Npc ID=7702, Four Fingers Wizard uses skill ID=15926, Flamebolt to attack, which misses the target. In addition, the flight animation is not visible. https://i.gyazo.com/0170b7e41e50667f7a9df74310e9eb5c.gif I fixed the attack with skill ID=15926, Flamebolt, but I don’t know how to fix the animation. https://i.gyazo.com/c576815cb0673022b989fd492c6d3453.gif

[Game] skill ID=15926, Flamebolt does not hit the target:

---

.env
AAEmu.Game/Dockerfile
AAEmu.Login/Dockerfile

- Update docker related files to use .NET 8 as per wiki

[Docker] Update to .NET 8

---

AAEmu.Game/Models/Game/Units/Route/Simulation.cs

- changed the calculation of movement distance in the MoveTo() method, similar to the Npc movement;

[Game] Changed in Simulation:

---

AAEmu.Game/Core/Managers/HousingManager.cs

Not sure how this bug got unnoticed for years ...

[Game] Fix house sales bug

---

AAEmu.Game/Core/Managers/SaveManager.cs
AAEmu.Game/Core/Managers/SkillManager.cs
AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Core/Network/Connections/GameConnection.cs
AAEmu.Game/Core/Packets/C2G/CSRemoveBuffPacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/Enums/MateState.cs
AAEmu.Game/Models/Game/Skills/Effects/SpawnEffect.cs
AAEmu.Game/Models/Game/Slaves/SlaveSpawner.cs
AAEmu.Game/Models/Game/Units/Slave.cs

- Now, if you want to test a car on Mirage Island, the sample car disappears and the test car appears. After 8 minutes, the test car breaks down and disappears. The sample car shows up.

[Game] Bug fix: "Test car Mirage don't work." #862

---

AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/GiveAppellation.cs

Implemented missing SpecialEffect GainAppellation (114)

[Game] Fixed Skill based title gains

---

AAEmu.Game/Core/Managers/HousingManager.cs
AAEmu.Game/Core/Packets/C2G/CSCreateHousePacket.cs

- Added allow recovery by default when creating a new house.
- Cleaned code for HousingManager.cs

[Game] Allow furniture recovery by default

---

AAEmu.Game/Core/Managers/ChatManager.cs
AAEmu.Game/Core/Managers/FamilyManager.cs
AAEmu.Game/Core/Packets/C2G/CSSendChatMessagePacket.cs

- Implemented the missing parts for family chat to work

[Game] Fix Family Chat

---

AAEmu.Game/Core/Packets/G2C/SCChatBubblePacket.cs
AAEmu.Game/Models/Game/Skills/Effects/BubbleEffect.cs
AAEmu.Game/Models/Game/Skills/Skill.cs

- Implemented the BubbleChat Skill Effect
- Implemented the Weight setting of Skill Effects

[Game] Added Bubble Chat and Skill Effects weights

---

AAEmu.Game/Core/Managers/UnitManagers/DoodadManager.cs
AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncFakeUse.cs

- Fixed the issue where doodads with multiple Fake Use Skills in one func group were only triggering the first one regardless of what option you picked.
- Cleaned some code

[Game] Fixed issues with some doodad usage

---

AAEmu.Game/Core/Managers/IndunManager.cs

Fixed typo

---

AAEmu.Game/Core/Packets/C2G/CSSendMailPacket.cs

- Fixes sending of mail from mailboxes on houses and the Any-Post Owl
Should fix #892

[Game] Fix sending of mail from mailboxes on houses and the Any-Post Owl

---

AAEmu.Game/Core/Managers/FamilyManager.cs
AAEmu.Game/Models/Game/Family.cs

Fixes a bug where the owner of a newly-created family would see a chat message containing invalid characters:

[Game] Fix broken chat message shown to owner of a newly-created family

---

AAEmu.Game/Data/Portal/recalls.json
AAEmu.Game/Data/Worlds/arche_mall_world/doodad_spawns.json

[Data] some cosmetics for Mirage;
[Data] fix for Solrid Peninsula location;
Data provided by Black Judge.

[Data] some fix for book of portals;

---

AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRecoverItem.cs

- eliminated duplication and left the storage of information about 'Slave' only in the '_slave WorldManager' dictionary;

[Game] Changes to SlaveManager:

---

AAEmu.Game/Core/Managers/TimedRewardsManager.cs

- when updating the number of work points in offline mode for an account, the SCCharacterLaborPowerChangedPacket package was sent to the X2EnterWorldResponsePacket package, which led to a failure in the numbering of packages in version 3.0.3.0 and it is possible that problems may arise in version 1.2;

[Game] TimedRewardsManager fix:

---

AAEmu.Commons/AAEmu.Commons.csproj
AAEmu.Commons/Network/BaseProtocolHandler.cs
AAEmu.Commons/Network/Core/Client.cs
AAEmu.Commons/Network/Core/Session.cs
AAEmu.Game/Core/Network/Connections/GameConnection.cs
AAEmu.Game/Core/Network/Connections/LoginConnection.cs
AAEmu.Game/Core/Network/Connections/StreamConnection.cs
AAEmu.Game/Core/Network/Game/GameProtocolHandler.cs
AAEmu.Game/Core/Network/Login/LoginProtocolHandler.cs
AAEmu.Game/Core/Network/Stream/StreamProtocolHandler.cs
AAEmu.Login/Core/Network/Connections/InternalConnection.cs
AAEmu.Login/Core/Network/Connections/LoginConnection.cs
AAEmu.Login/Core/Network/Internal/InternalProtocolHandler.cs
AAEmu.Login/Core/Network/Login/LoginProtocolHandler.cs

Not sure if it's worth updating, but here it is anyway.

Update NetCoreServer dependency from v2.0.3 to v8.0.7

---

AAEmu.Game/Utils/IdManager.cs

This update might help in preventing duplicate ObjId issues on slower servers.
- Added lock to ``ReleaseId``
- Cleaned the code in ``IdManager``

[Game] Modernize IdManager

---

AAEmu.Game/Core/Managers/LocalizationManager.cs
AAEmu.Game/ExampleConfig.json
AAEmu.Game/Models/AppConfiguration.cs

Added ``DefaultLanguage`` entry to the game server's ``Config.json`` so that the locale is no longer hard-coded.
If you want something else than English as your default server language on a existing server, then add the related entry to your config.

[Game] Added DefaultLanguage setting

---

AAEmu.Game/Core/Managers/ExperienceManager.cs
AAEmu.Game/Core/Managers/SkillManager.cs
AAEmu.Game/Models/Game/Char/CharacterSkills.cs
AAEmu.Game/Models/Game/Skills/Templates/PassiveBuffTemplate.cs
AAEmu.Game/Models/Game/Skills/Templates/SkillTemplate.cs

- Fix for #934
- Fixed the wrong calculation of required points for learning Passive Skill
- Fixed the calculation of useable skill points per level
- Replaced byte with ``AbilityType`` for ``AbilityId`` values
- A bit of code cleaning inside CharacterSkills.cs

[Game] Fixed Skill Points required

---

AAEmu.Game/Services/WebApi/Controllers/AuctionController.cs

New WebAPI Controller for adding items to the Auction House, even if the referenced character is offline.
Example api JSON Payload to POST to target ``/api/auction/add``
```JSON
{
"itemId": 1234,
"quantity": 10,
"price": 5000,
"duration": 3600,
"clientId": 5678,
"clientName": "PlayerName"
}
```

[WebAPI] Add controller for AuctionHouse

---

AAEmu.Game/Core/Managers/World/SpawnManager.cs

- For each spawnerId, the templateId we need is usually specified in template.Name;

[Game] Fixed selection of spawnerId for the current templateId:

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Models/Game/Items/Templates/ItemSet.cs
AAEmu.Game/Models/Game/Skills/Skill.cs

- Added loading for ``item_sets`` and ``item_set_items`` tables
- Added consumption of the items when SkillEffect has ``ItemSetId`` set
These are required for stuffing Larders, some of the campfire function, and chicken coops.
This fixes #965

[Game] Added ItemSet for SkillEffects

---

AAEmu.Login/Core/Controllers/GameController.cs

[Login] Fixed the issue of long waiting times for the list when there are offline servers

[Login] Fixed the issue of long waiting times for the list when there are offline servers

---

AAEmu.Game/Core/Managers/SubZoneManager.cs

- Added a null-check for when a zone doesn't have sub-zones

[Game] Fixed issues with zone without sub-zones

---

AAEmu.Game/Models/Game/Char/Character.cs

Co-authored-by: NL0bP
Fixed a bug where the attacker's HP was reduced to 1 during a duel.

 [Game] Fixed Duel

---

AAEmu.Game/Core/Packets/G2C/SCErrorMsgPacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterCraft.cs

- now packs are crafted as expected, no more than one.
- ordinary items are crafted into inventory.
- it turned out that you need to send the correct SCErrorMsgPacket to cancel crafting.

[Game] Crafting bug fixed:

---

AAEmu.Game/Core/Managers/MailManager.cs

- Changed how items for the quest reward /supply mails are sent.

[Game] Updated Mail quest rewards

---

AAEmu.Game/Core/Managers/World/WorldManager.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/BaseCombatBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/AlertBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/IdleBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/Common/RoamingBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/Flytrap/FlytrapAttackBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Behaviors/WildBoar/WildBoarAttackBehavior.cs
AAEmu.Game/Models/Game/AI/v2/Framework/Behavior.cs
AAEmu.Game/Models/Game/AI/v2/Framework/NpcAi.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/NPChar/Npc.cs
AAEmu.Game/Models/Game/Skills/Effects/AggroEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/NpcSpawnerSpawnEffect.cs
AAEmu.Game/Models/Game/Skills/SkillControllers/LeapSkillController.cs
AAEmu.Game/Models/Game/Units/BaseUnit.cs
AAEmu.Game/Models/Game/Units/Route/Track.cs
AAEmu.Game/Models/Game/Units/Unit.cs
AAEmu.Game/Models/Game/World/GameObject.cs
AAEmu.Game/Models/StaticValues/TagsEnum.cs
AAEmu.Game/Scripts/Commands/Dist.cs
AAEmu.Game/Scripts/Commands/Rotate.cs
AAEmu.Game/Scripts/Commands/TestAI.cs
AAEmu.Game/Utils/MathUtil.cs

- Enhanced AI to have a more realistic alert and aggro mechanics while taking data from the DB for range and field of view and taking into account stealth buffs.
- Fixed the ``MathUtils.InFront()`` to actually calculate the angles correctly.
- Enhanced AggroTable handling. You will now immediately go out of combat after you killed all targets that have Aggro on you.
- Added angle information to the ``/distance`` GM command.

[Game] Enhanced AI Alert and Combat Aggro

---

AAEmu.Game/Models/Game/Char/CharacterCraft.cs

This fix closes #1009
Crafts would fail if they didn't have materials

[Game] Fix crafting with no materials

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Packets/C2G/CSSellItemsPacket.cs
AAEmu.Game/Scripts/Commands/ShowInventory.cs
AAEmu.sln.DotSettings

- Improved check of what items need to be saved. This should prevent the saving error some people are getting.
- Updated ``/showinventory`` GM command to display slot related errors
- Code cleaning in ``ItemManager.cs``

[Game] Fixed issues with BuyBack items

---

AAEmu.Game/Scripts/Commands/Nwrite.cs

- Added some of the missing ``Savannah Elephant Bone ( 3875 )`` doodads to be able to complete the quest ``From Dust to Dust ( 3644 )``
- Updated the ``/write`` GM command to clamp the rotation values.

[Data] Added doodads for quest From Dust to Dust ( 3644 )
