AAEmu.Game/Models/Game/World/Region.cs

Offsets were not calculated correctly resulting in out of bounds errors if the unit or doodad count was too large to send in one go.

Out of range fix in RemoveFromCharacters()

---

SQL/aaemu_login.sql
docker-compose.yaml

Removed reference to the variable `saved_cs_client ` in login SQL which doesn't exist; causing a MySQL error when running the SQL on a fresh instance: `ERROR 1231 (42000) at line 20: Variable 'character_set_client' can't be set to the value of 'NULL'`
Tested by running a clean container and volume in docker and entering the game world on a new character.
Updated docker-compose to use mysql 8.0

Login sql bugfix & docker-compose mysql now uses version 8.0

---

.github/workflows/dotnetcore.yml
.travis.yml
AAEmu.Commons/AAEmu.Commons.csproj
AAEmu.Game/AAEmu.Game.csproj
AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Managers/SaveManager.cs
AAEmu.Game/Core/Managers/UnitManagers/NpcManager.cs
AAEmu.Game/Core/Packets/C2G/CSBuyCoinItemPacket.cs
AAEmu.Game/Core/Packets/C2G/CSBuyItemsPacket.cs
AAEmu.Game/Models/Game/Char/CharacterCraft.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncPurchase.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRatioChange.cs
AAEmu.Game/Models/Game/Items/Item.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs
AAEmu.Game/Models/Game/Merchant/MerchantGoods.cs
AAEmu.Game/Models/Game/Quests/Acts/QuestActSupplyItem.cs
AAEmu.Login/AAEmu.Login.csproj
AAEmu.Tests/AAEmu.Tests.csproj

Move to .NET Core 3.1 (make sure to move your debug folder content)
Vocation/Honor shop now work correctly
Fixed basic mirage shopping
Reduced SaveManager clutter
Move some INFO logs to DEBUG, and removed save information of things that weren't changed.
Backpack shopping now equips the backpack on buy.

Various shop fixes and .NET Core 3.1

---

AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs

Equipping a two-handed weapon now correctly tries to unequip the offhand first.
Different non-stackable items (i.e. weapons) can now be location-swapped.

[Items] Fix two-handed weapon equips

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Managers/World/SpecialtyManager.cs
AAEmu.Game/Models/Game/Char/CharacterCraft.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/DoodadObj/DoodadSpawner.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRecoverItem.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs
AAEmu.Game/Models/Game/Items/SlotType.cs
AAEmu.Game/Models/Game/Skills/Effects/PutDownBackpackEffect.cs
AAEmu.Game/Models/Game/World/Spawner.cs
AAEmu.Game/Scripts/Commands/ShowInventory.cs
SQL/aaemu_game.sql
SQL/updates/2020-12-09_aaemu_game_items.sql

Crafting items now properly sets the CrafterId of the item.
Trade-packs will now retain their crafter information when put down and picked back up.
Time to steal some trade-packs for profit !
Added new item container System that is used for doodad ItemId storage.
Updated /showinv to allow 255 as container id for system
Updated MySQL Items slot_type ENUM()
Note: Dropped trade-packs are not yet persistent between reboots !

[Items] CrafterId

---

AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Core/Managers/World/SpawnManager.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/SpawnSlave.cs
AAEmu.Game/Models/Game/Units/Slave.cs
AAEmu.Game/Models/Game/World/Transform/PositionAndRotation.cs
known_issues.txt

- Changed boat unsummoning so that the boat doesn't immediately disappear when unsummon, but instead are delayed by their summoning time.
- You can now bind to a slave's slave without crashing!
In plain English this means that you can now grab a (harpoon) canon without getting kicked from the game.

[Game] Boat unsummon

---

AAEmu.Game/Models/Game/World/Transform/Transform.cs

Uncommented a SetPosition in Transform that was preventing drowning (and likely other things like zone borders) to take effect.
I'm sure there was a reason this was commented in the first place by me, but I can't remember why this was.
So uncommented for now, and let it probably break some other stuff ^_^

[Game] Fix: Drowning

---

AAEmu.Game/Core/Managers/TaskManager.cs
AAEmu.Game/Models/Tasks/Doodads/DoodadFuncFinalTask.cs

Added a NULL-check to handle doodad respawns that don't have a respawn timer and don't have a FuncTask attached either.
This prevents a server-crash in case FuncTask is NULL

[Game] DoodadFuncFinalTask null check

---

AAEmu.Game/Core/Managers/World/WorldManager.cs

Added fix so that non-Units and non-Doodads will still show up if teleporting nearby. (e.g. Houses)

[Game] Fix: object spawning after teleport

---

AAEmu.Game/Core/Managers/HousingManager.cs
AAEmu.Game/Core/Packets/C2G/CSDecorateHousePacket.cs

Fixed the issue where placing things on sloped surfaces in or on a house would result in the furniture having the wrong rotation.
(turns out it was something left over from debugging long time ago)

[Game] Furniture, rotation

---

AAEmu.Game/Models/Game/Skills/CastAction.cs
AAEmu.Game/Models/Game/Skills/Effects/CraftEffect.cs
AAEmu.Game/Models/Game/Skills/Skill.cs

Fixed CastSkill.TlId exporting the wrong type
Items no longer get consumed in Skill.ApplyEffect() if the skill got Cancelled
Labor is no longer consumed in EndSkill() is the skill was cancelled
Added code to verify building steps of building a shipyard at the end of a build step in a similar way as done for buildings.

[Game] (Shipyard) Skill Cancelling

---

AAEmu.Game/Models/Game/Skills/CastAction.cs
AAEmu.Game/Models/Game/Skills/Effects/CraftEffect.cs
AAEmu.Game/Models/Game/Skills/Skill.cs

Fixed CastSkill.TlId exporting the wrong type
Items no longer get consumed in Skill.ApplyEffect() if the skill got Cancelled
Labor is no longer consumed in EndSkill() is the skill was cancelled
Added code to verify building steps of building a shipyard at the end of a build step in a similar way as done for buildings.

[Game] (Shipyard) Skill Cancelling (#356)

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Items/EquipmentContainer.cs
AAEmu.Game/Models/Game/Items/ItemContainer.cs
AAEmu.Game/Models/Game/Units/Unit.cs

Added code to valid if a item is allowed in a specific equipment slot.
Also fixes issues to existing invalid items in slots by orphaning them.
Auto-unequipping of gliders when adding a backpack should now work correctly, and properly fail if the current backpack can't be unequipped.

[Game] Valid Equipment Check

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Managers/ModelManager.cs
AAEmu.Game/Core/Managers/UnitManagers/NpcManager.cs

Fixed the floating heads issue for NPCs, by making a better handler for random hair looks for NPCs, that don't have total_character_customs defined for their model.

[Game] Fix: NPC floating heads

---

AAEmu.Game/AAEmu.Game.csproj

Removing all warnings from project build time.
Changed Ionic.Zlib and Jitter to use Core enabled versions.

Fixing package warnings on build time

---

AAEmu.Commons/Utils/Updater/MySqlDatabaseUpdater.cs

Made it so the MySQL Auto Updater does not toss a useless exception anymore when it doesn't find files.

[All] Fix: MySqlDatabseUpdater warning

---

AAEmu.Commons/Utils/Updater/MySqlDatabaseUpdater.cs

In addition to YES you can now also use SKIP to skip updating SQL files, but mark them as installed. This should only be used during development of your own updates.

[All] Update: MySqlDatabaseUpdate can now be skipped

---

AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Scripts/Commands/Damage.cs

I wondered why damage was hardcoded at only 100 HP, so I decided to tweak it
Usage: /damage <health percentage> (between 1 and 99)

/damage GM command is now based on health percentage

---

AAEmu.Game/Core/Packets/C2G/CSRepairSingleEquipmentPacket.cs

Commented out unnecessary data reads from CSRepairSingleEquipmentPacket, which caused the server to fail;

Corrected the structure of CSRepairSingleEquipmentPacket;

---

AAEmu.Login/Core/Controllers/GameController.cs
AAEmu.Login/Core/Network/Connections/LoginConnection.cs
AAEmu.Login/Core/Network/Login/LoginProtocolHandler.cs
AAEmu.Login/Core/Packets/C2L/CAListWorldPacket.cs
AAEmu.Login/Core/Packets/G2L/GLRegisterGameServerPacket.cs
AAEmu.Login/Core/Packets/L2C/ACWorldCookiePacket.cs

Changed the Login server so it can also accept a hostname for the server name field in the DB. It will try to resolve the name using a DNS lookup and then just locally store the IP for use on connections.
Changed ACWorldCookiePacket so it will use the same IP as used to connect with if the client is on the same machine as the login server.
This is a debugging feature that allows you to run a local login + game server using a local client, while still allow others to connect using your external IP provided in the DB.
This requires the port binding is be set to the default asterisk (*), and assumes the game server is running on the same machine as the login server.

[Login] Allow hostnames and local connections

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs
AAEmu.Game/Models/Game/Items/Templates/BackpackTemplate.cs

Fixes a bug where you could drag a equipped trade-pack back to your inventory making it stuck there as you are not allowed to re-equip it.

[Game] Fix tradepack unequip bug

---

SQL/aaemu_game.sql

Added the missing update from 28th July 2022 to the main sql for installation
This adds the missing fields for timed items

[SQL] Fixed default aaemu_game.sql

---

AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRatioChange.cs

[Game][Doodad] Fixed DoodadFuncRatioChanges;
[Game][Quest] Now quest 1135 is working correctly:
- chests Id=5171 "Stolen Goods" now counts everything in a row;
- chests Id=5171 "Stolen Goods" can be of two types;

Quest 1135 fix

---

AAEmu.Game/Core/Managers/FishSchoolManager.cs
AAEmu.Game/Core/Managers/UnitManagers/CharacterManager.cs
AAEmu.Game/Core/Network/Game/GamePacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/DoodadObj/Static/DoodadConstants.cs
AAEmu.Game/Models/Game/Skills/Effects/CraftEffect.cs
AAEmu.Game/Models/StaticValues/DoodadConstants.cs

- Added a lock to generating the FishFinder doodads list to avoid exceptions.
- Changed how shortcut bars are saved/loaded so they no longer crash the connection if something went wrong with them.

[Game] Fix: action bar, fish-finder

---

AAEmu.Game/Scripts/Commands/Kill.cs

The /kill command would set the unit's HP to 0 but the data wasn't being broadcast to clients due to ReduceCurrentHp doing nothing if the current HP is 0.
ReduceCurrentHp should effectively be setting the HP to 0 anyway, so there's no need to set it manually in the kill command.

[Script] Fix Kill Command

---

AAEmu.Game/Core/Packets/C2G/CSSelectCharacterPacket.cs
AAEmu.Game/Models/Game/Units/Unit.cs

Once the buffs are added the passives should generally just work, however I think some are still missing the server side logic. The ones that I've verified are working are:
- Portal Mastery (Reduces the cooldown and cast time of the Recall ability by 30%.)
- Catlike Reflexes (Reduces fall damage by 20%)
- Endurance Training (
Allows Elves to hold their breath 20 seconds longer than other races) https://github.com/AAEmu/AAEmu/issues/447
- Lithe Flow (Increases the swim speed of elves by 5%)

[Game] Implement racial passives

---

AAEmu.Game/Models/Game/Skills/Buff.cs

- to fix the work of some quests was, as it turned out incorrectly, commented out line 172;
- effects began to disappear immediately after their completion;

[Game] reverted changes to the Buff.cs Exit() method:

---

AAEmu.Game/Core/Managers/World/SphereQuestManager.cs
AAEmu.Game/Models/Game/Units/Route/Simulation.cs

Replace en-US with culture invariant for some of the functions.
This should be functionally the same.
This change was needed to try and fix a issue where people are having problems running the server on platforms that don't have that culture installed (usually inside docker)

[Game] Removed culture specific settings

---

AAEmu.Game/Models/Game/AI/v2/Behaviors/BaseCombatBehavior.cs

If the character is further away than the NPC by returnDistance meters, the NPC will remove the aggro. 
If the NPC continues to chase the character and it does not exceed returnDistance, it will remove the aggro if the NPC exceeds absoluteReturnDistance

Fixed NPCs returning to their starting position.

---

AAEmu.Game/Core/Managers/MateManager.cs
AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Core/Packets/C2G/CSRemoveBuffPacket.cs
AAEmu.Game/Core/Packets/C2G/CSStartSkillPacket.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/Blink.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/RemoveDoodad.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Skills/Templates/BuffTemplate.cs
AAEmu.Game/Models/Game/Units/Buffs.cs
AAEmu.Game/Models/Game/Units/Mate.cs

In SlaveManager Added removal of buffs for a character when he leaves from the Slave
In CSRemoveBuffPacket Added removal of Gliding buffs for flying mounts
In CSStartSkillPacket Modified the use of skills to send Mate and Slave as Caster
In Blink Added check if a character is sitting on a mount, then forced to do UnMount before using the teleport skill
In RemoveDoodad Added removal of Doodads when using certain skils (for example: ID - Jousting Lance Charge)
In BuffTemplate added a check if a main checking buff is on mount (Example: ID - 26138 Lightning Stealth)
In Skills added a check if the character is sitting on the mount, the UseSkill trigger is used to remove the buffs from the mount
Also added a check if the character is on mount and uses allowed skills to use, then forcibly …

Fix mounts skills and buffs

---

AAEmu.Game/Models/Game/Skills/Buff.cs

Fixed the faction change for NPCs. Fix for quest - 2396 and similar quests where the initial faction change is due to NpcControllEffect, and then a buff was applied that should bring the faction back. 
Example: Quest - 2396
Because NpcControllEffect (case NpcControlCategory.AttackUnit) changes the NPC's faction to FactionsEnum.Monstrosity (115), when the buff was applied, faction 115 is passed to the buff, instead of 101, which was the NPC's original faction.

[Game] Fixed the faction change for NPCs

---

AAEmu.Game/Models/Game/Units/Mate.cs
AAEmu.Game/Models/Game/Units/Slave.cs

Fixed the display of a character sitting on pets or slaves when the character comes from another region
How it works now: 
If a character is sitting on a mate or slave and comes from another region, only the mate or slave will be displayed for the other character, and the character will be "invisible" and will be displayed at 5000 meters away

[Game] Fixed display of sitting character on pets or slaves

---

AAEmu.Game/Core/Managers/QuestManager.cs
AAEmu.Game/Core/Packets/G2C/SCQuestContextResetPacket.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterQuests.cs
AAEmu.Game/Models/Game/Quests/Static/QuestDetail.cs
AAEmu.Game/Models/Game/Quests/Templates/QuestTemplate.cs
AAEmu.Game/Models/Tasks/Quests/QuestDailyResetTask.cs
AAEmu.Game/Scripts/Commands/QuestCmd.cs
AAEmu.Game/Utils/QuestCommandUtil.cs

Added code to handle daily quest resets.
To minimize overhead it only reset current online player's quests at local machine midnight.
It also checks at character login if the last leave time was the day before or not, and triggers resets as needed.

[Game] Daily Quest Reset

---

AAEmu.Game/AAEmu.Game.csproj
AAEmu.Game/Configurations/Specialty.json
AAEmu.Game/Core/Managers/World/SpecialtyManager.cs
AAEmu.Game/Models/AppConfiguration.cs
AAEmu.Game/Models/Game/Configurations.cs
AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs

Trade pack ratios were not updated as expected. It would keep lowering the % based on the total amount of packs set as the pack counter never got reset.
There was a wrong null check in ItemContainer that would make it so you wouldn't get any buffs or bonuses for new items that where instantiated outside of a item container.

[Game] Fix: Trade pack Ratio and Overburdened

---

AAEmu.Game/Data/Worlds/main_world/npc_spawns.json

Fixed z-coordinate of quest npcs 3425 Nubo in Tigerspine Mountains, 5070 Aier Disciple Rei in Villanelle, 2926 Captain Frelli,2939 Cannon Officer Wyld,2940 First Mate Lamelda,790 Garriot Blackbeard (in the West) and sailors in Forbidden Shore at Solis Headlands. Added missing doodads 4430 Chair of Fertility ,quest doodads 2642 Pebble, 5900 Hasla's Forgotten Memories.

[Data] Fixed npc and doodads

---

AAEmu.Game/AAEmu.Game.csproj
AAEmu.Game/Core/Managers/TaskManager.cs

In a way to reduce the Total CPU cycles over time
- Reduce allocation to one reference during while loop
- Using Threading.Tasks instead of old Thread approach.

TaskManager improvements

---

AAEmu.Game/Core/Packets/G2C/SCLootBagDataPacket.cs

Fixed a crash and inventory corruption issue that *could* occur whenever you opened a corpse/loot spot using G instead of F to loot all.

[Game] Fix: Open Loot Bag

---

AAEmu.Game/Models/Game/Faction/SystemFaction.cs
AAEmu.Game/Models/Game/Skills/Effects/BuffEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Units/BaseUnit.cs

This PR fixes issues with AoE skills like ``Concussive Arrow (Archery)`` that would fail to properly AoE, could miss and could trigger Bloodlust as well (multiple bugs)
- Default undefined factions to Friendly instead of Hostile
- Re-enable the auto-purpling prevention check
- Code cleaning
- Fixed AoE targetting
- Added support for always-hit skills
- Added support for zone protection to ``CanAttack`` to protect NPCs and Players that are in their faction zones. (can no longer use AoEs to force-hit them)

[Game] Fix faction check and AoE related hits

---

AAEmu.Game/Models/Game/Skills/Effects/CraftEffect.cs

Changed ``CraftEffect`` so that actions without a ``wi`` that does not have a valid ``wi_group`` still continue to trigger a ``EndCraft()``

[Game] Fix crafts without WI

---

AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs

- if the AppConfiguration.Instance.HeightMapsEnable setting is disabled, then damage is disabled, since the bottom depth is incorrectly calculated;
- corrected the formula for calculating the distance between the bottom of the ship and the surface of the earth;

[Game] fix damage to ships on the high seas:

---

AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Char/CharacterActability.cs
AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncFinal.cs
AAEmu.Game/Models/Game/Skills/Skill.cs

- Doodads ignore max distance again to temporary resolve issues with doodads on player buildings.
- DoodadFuncFinal now gets their PhaseTime properly restored on server reboot. (would previously not restore their end time correctly.
- Changed ``ChangeLabor()`` so it will not generate a max proficiency popup every time you craft when already at the maximum.

[Game] Various small fixes

---

AAEmu.Game/Models/Game/Quests/Acts/QuestActObjItemGather.cs

- Fixed QuestActObjItemGather from taking too many items when completing a quest by capping it, rather than taking the objective value. (e.g. Quest Daily quest a Lily Offering from the Nui Priestess)

[Game] Fix Quest taking too many item on complete

---

AAEmu.Game/Core/Managers/World/AreaTriggerManager.cs
AAEmu.Game/Models/Game/DoodadObj/Doodad.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/RemoveDoodad.cs
AAEmu.Game/Models/Game/World/AreaTrigger.cs
AAEmu.Game/Models/Tasks/Doodads/DoodadFuncCloutTask.cs

- Some changes to make skills like Vitalism - **Twilight** to work correctly.
- Added some code, so that when a ``AreaTrigger`` gets removed the Units inside it get a proper ``OnLeave()`` event.
- Added some code to ``Doodad``, that when removed, they also remove the related AreaTrigger to this doodad

[Game] Fix - Doodad Area Trigger OnDelete

---

AAEmu.Game/Models/Game/Units/Slave.cs

Fixed a bug where trying to show a ownerless Slave would result in a null exception and disconnect.
This fixes Issue #788

[Game] Fix - Ownerless Slaves

---

AAEmu.Game/Models/Game/Housing/House.cs

Fixed the issue where the saved recovery state was not applied to the house packet.

[Game] Fixed missing allow furniture recovery flag

---

AAEmu.Game/Core/Managers/QuestManager.cs
AAEmu.Game/Models/Game/Quests/Quest.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Tasks/Skills/EndChannelingTask.cs

- Fixed the issue where non-consume useable items would get consumed anyway.
- Added quest handler for using items that don't consume (when used as a channeling skill).

[Game] Fix quest item use handling

---

AAEmu.Game/Models/Game/Items/Loots/LootPack.cs

Changed the item add function for adding items from lootpack to use generic ``TryAddNewItem`` instead of adding directly to the bag. This fixes the issues with larders and any other lootpack that would result in a backpack.

[Game] Fix: Add item from loopack

---

AAEmu.Game/Models/Game/AI/v2/Behaviors/BaseCombatBehavior.cs
AAEmu.Game/Models/Game/NPChar/Npc.cs

Seems the movement speed multiplier for NPC AI got broken again.

[Game] Fix NPC movement speed multiplier

---

AAEmu.Game/Models/Game/Skills/Plots/Tree/PlotTargetInfo.cs
AAEmu.Game/Models/Game/Skills/Skill.cs

- since there was a type cast error, I added a choice between: positionTarget, position2Target and position3Target;
- also changed the generator for objId from uint.MaxValue to ObjectIdManager.Instance.GetNextId;
- Attention! This needs a check to see if the objId value used is freed;

[Game] if you try to shoot from an armored tank the client disconnects:

---

AAEmu.Game/Models/Game/NPChar/Npc.cs

- if a character fires a cannon at an Npc, the error InvalidCastException: Unable to cast object of type 'Slave' to type 'Character' appears;

[Game] InvalidCastException error fix:

---

AAEmu.Game/Core/Packets/G2C/SCCraftFailedPacket.cs
AAEmu.Game/Models/Game/Char/CharacterCraft.cs
AAEmu.Game/Models/Game/Skills/Skill.cs

- When crafting simultaneously a large number of resources on machines, Labor Power goes beyond the minimum permissible values ​​(less than 0). As a result, you can craft an endless amount of resources, even if the player does not have enough Labor Power.
- Nothing I can do better than dummy cycles of the crafting skell so that the crafting doesn't hang. Superfluous cycles can be interrupted.
- Added packet SCCraftFailedPacket (needs fixing);

#739 [Game] fixed negative LP when crafting materials:

---

AAEmu.Game/Models/Game/Skills/Effects/SpecialEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/Cooldown.cs

- in the Cooldown class, SkillModifiers are taken into account when calculating cooldownDuration;
- added check "SpecialEffectTypeId == SpecialType.Projectile" to the SpecialEffect class;
These changes are seen in the Genesis code.

[Game] Update Effects:

---

SQL/aaemu_game.sql

The default installer ``aaemu_game.sql`` was missing the newest additions related to pet gear from PR #832

[SQL] Missing update for pet gear

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Managers/World/SpecialtyManager.cs
AAEmu.Game/Core/Network/Game/GameNetwork.cs
AAEmu.Game/Core/Packets/C2G/CSOffsets.cs
AAEmu.Game/Core/Packets/C2G/CSRequestSpecialtyCurrentPacket.cs
AAEmu.Game/Core/Packets/G2C/SCSpecialtyCurrentPacket.cs
AAEmu.Game/Models/Game/Items/Templates/ItemTemplate.cs
AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/PlayUserMusic.cs

- Implemented the functionality of the Trade Rate Window where you can see the current rates from and to zones.
- Changed ItemTemplate.Category_Id to ItemTemplate.CategoryId
- Changed SpecialtyManager's implementation of _priceRatios and _soldPackAmountInTack so they now use ZoneGroup instead of ZoneKey (which was technically a potential bug)

[Game] Added Specialty Trade rates panel

---

AAEmu.Game/Models/Game/Char/CharacterPortals.cs

Added a additional null-check in ``CharacterPortals.PopulateDistrictPortals`` to help mitigate invalid subzone entries preventing player from logging in is there were errors with the DB or configuration settings.

[Game] Added null check in PopulateDistrictPortals

---

AAEmu.Game/Core/Managers/HousingManager.cs
AAEmu.Game/Core/Packets/G2C/SCUnitStatePacket.cs
AAEmu.Game/Models/Game/Housing/House.cs
AAEmu.Game/Models/Game/Units/Unit.cs

- Made Unit's Expedition virtual so it can be overridden in House.
- Added code that always grabs a house's guild from its owner.
- Fixed a small issue where CoOwner was used incorrectly
- Added a few comments to SCUnitStatePacket
This should fix issue #899

[Game] Fixed guild house permissions

---

AAEmu.Game/Scripts/Commands/Teleport.cs

Once again a minor thing but it'd seem the current sungold teleport command actually takes you to Exeloch. I've changed the coordinates to match those of Sungold Fields.

Fixed the wrong coordinates on the Sungold Fields teleport command.

---

AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Models/Game/Skills/Effects/SpawnEffect.cs

- Fixed Slave spawning to properly ignore slave bindings belonging to houses (canon bug was from a tower)
- Fixed spawn rotation by adding missing DegToRad function on the angle arguments in SpawnEffect

[Game] Fix Test Timbre Coupe spawn

---

AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/TeleportToUnit.cs

Fixes the Shadow Step skill's teleport to correctly place the caster behind the target, rather than to the side.
Also implements randomisation of the distance and rotation, though that isn't used by Shadow Step.

[Game] Fix TeleportToUnit for correct positioning of Shadow Step skill

---

AAEmu.Game/Models/Game/Skills/Effects/SpawnEffect.cs

Adds `PosDirId` and `OriDirId` support for NPC-based SpawnEffects, which fixes the General Merchant's Cushion (28440), Warehouse Manager's Cushion (28441), and Elite Merchant's Cushion (28386), spawning them in the correct position and rotating them to face the player.
It would be good to check the code still works as intended in other cases, but I'm not sure what else to test with. Same for supporting `BaseUnitType.Slave`, I'm also not sure what to test with.
Should fix https://github.com/AAEmu/AAEmu/issues/903

[Game] Implement PosDirId and OriDirId for NPC-based SpawnEffect

---

AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Core/Managers/UnitManagers/DoodadManager.cs
AAEmu.Game/Core/Managers/World/BoatPhysicsManager.cs
AAEmu.Game/Core/Managers/World/SpawnManager.cs
AAEmu.Game/Core/Packets/C2G/CSDespawnSlavePacket.cs
AAEmu.Game/Core/Packets/C2G/CSDestroyItemPacket.cs
AAEmu.Game/Core/Packets/C2G/CSDestroySlavePacket.cs
AAEmu.Game/Models/Game/Char/Inventory.cs
AAEmu.Game/Models/Game/Items/Containers/ItemContainer.cs
AAEmu.Game/Models/Game/Items/Item.cs
AAEmu.Game/Models/Game/Items/SummonMate.cs
AAEmu.Game/Models/Game/Items/SummonSlave.cs
AAEmu.Game/Models/Game/Units/BaseUnitType.cs
AAEmu.Game/Models/Game/Units/Slave.cs
SQL/aaemu_game.sql
SQL/updates/2024-05-04_aaemu_game_slaves_update.sql

- Added various fields to the ``slaves`` table to allow saving of child slaves like canons.
- Added unused function to delete vehicles
- Fixed the issue where child doodads from slave that are not persistent (or newly created) would not be missing their InitDoodad function, resulting in timer functions to not work server-side.
- Replaced ItemContainer.CanDestroy with Item.CanDestroy
- Added Item.OnManuallyDestroyingItem that is called just before a item gets destroyed from tossing it
- RemoveActiveSlave now has a added argument to allow unsummoning even when the vehicle is carrying items.
Note: if you have previously bugged vehicles, you can run the following MySQL query to remove all of the vehicle doodads so they will get regenerated on their next summon
```SQL
DELETE FROM `doodads` …
```

[Game] Fixed persistent Vehicle saving

---

AAEmu.Game/Core/Managers/ItemManager.cs
AAEmu.Game/Core/Managers/TeamManager.cs
AAEmu.Game/Models/Game/NPChar/Npc.cs
AAEmu.Game/Models/Game/NPChar/Tagging.cs
AAEmu.Game/Models/Game/Team/TeamMember.cs
AAEmu.Game/Models/Game/Units/Unit.cs

- Added Tagging.cs to control tagging system.
- Hitting an enemy for the first time now tags it to the player (or mate/pet owner) and any party/raid members in range.
- Per 1.2 ArcheAge, dealing more than 50% mob health in damage from a single player or a party/raid will steal the tag on that enemy.
- Modified GetActiveTeam() in TeamManager.cs to be public, for the tagging system to access.
- Rewrote DoDie() in NPC.cs to correctly process kill rights for looting and XP distribution: -- The owning tagger or party are processed.
-- XP scaling is in place for levels. Before the Party reduction, individual XP award is calculated based on player level vs enemy level. At 1:1, it is 100% of XP. It decreases by 10% for every level below the player the enemy is, until it caps at 0 XP at -10 …

[Game] Tagging added for kill credit, XP, and Loot (with Rotate Winner and Free For All)

---

AAEmu.Game/Models/Game/Skills/Effects/BuffEffect.cs
AAEmu.Game/Models/Game/Skills/Effects/DamageEffect.cs
AAEmu.Game/Models/Game/Skills/Skill.cs
AAEmu.Game/Models/Game/Units/Unit.cs

- Effects now correctly targets units when TargetNpcTagId is set
- Added check that prevents players from getting the Retribution buff (purpling) from attacking NPCs

[Game] Added TargetNpcTagId check for effects

---

AAEmu.Game/Services/WebApi/Controllers/AuctionController.cs

New capability in the AuctionController to handle two GET requests. One returns the entire auction house data (/api/auction/list) and the other can provide a filtered result (/api/auction/search).
Available filters include (but could be extended if needed): itemId, clientName, stackSize, directMoney, bidMoney, bidderName
Example python script for using search via API with filters (filters are optional):
```
import requests
base_url = "http://127.0.0.1:1280/api/auction"
def search_auction_items(filters):
try:
response = requests.get(f"{base_url}/search", params=filters)
if response.status_code == 200:
auction_items = response.json()
print("Filtered Auction Items:")
print(auction_items)
else:
print(f"Failed to retrieve auction items. Status code: {response.status_code}") …
```

[WebAPI] Update controller for AuctionHouse (Search/Filter)

---

AAEmu.Login/Core/Controllers/GameController.cs
AAEmu.Login/ExampleConfig.json
AAEmu.Login/Models/AppConfiguration.cs

Added a ``SkipHostResolve`` option to ``Config.json`` to allow the login server to skip host name resolving and simply processing the raw IP used in the ``game_servers`` table.
This can be useful for making specific setups work correctly. Recommended to keep this setting ``false`` unless it is consistently resolving to the wrong IP when starting.

[Login] Added option to skip the host resolving

---

SQL/aaemu_game.sql

Before err says:
```
ERROR 1064 (42000) at line 35: 
You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version
for the right syntax to use near '' at line 1
```
Previously, the trigger definition was causing a ERROR 1064 (42000) due to incorrect usage of semicolons within the BEGIN ... END block.
Changes made:
Updated the trigger definition to use a custom delimiter (//) allowing the use of semicolons within the BEGIN ... END block.
Reverted back to the default delimiter (;) after the trigger definition.
With these changes, the trigger update_timestamps should now be created without any syntax errors.

Update aaemu_game.sql to fix syntax err.

---

AAEmu.Game/Core/Managers/IndunManager.cs
AAEmu.Game/Core/Managers/SkillManager.cs
AAEmu.Game/GameData/NpcGameData.cs
AAEmu.Game/Models/Game/DoodadObj/Funcs/DoodadFuncRequireQuest.cs
AAEmu.Game/Models/Game/Indun/Dungeon.cs
AAEmu.Game/Models/Game/NPChar/Npc.cs
AAEmu.Game/Models/Game/NPChar/NpcEvents.cs
AAEmu.Game/Models/Game/NPChar/NpcSpawner.cs
AAEmu.Game/Models/Game/NPChar/NpcSpawnerNpc.cs
AAEmu.sln.DotSettings

- Added null-check to ``SkillManager.GetNpSkillTemplate``
- Fixed missing ``s`` typo in ``GetNpSkill``
- Changed ``DoodadFuncRequireQuests`` to be ignored if caster is not a ``Character``. This is mostly used in Doodad's initial state, and would work better if it's a actual spawn check rather than a conditional check on it's own. This is likely supposed to check the caster's killer if it's called from a OnDeath event. But works good enough to get the quests done for now.
- Moved the NPC event functions from ``Dungeon`` into a new partial class Npc file ``NpcEvents.cs`` and linked it to the standard spawners.
- Lowered the logging level of dungeon notifications

[Game] Moved NPC events out of dungeons and onto all NPCs

---

AAEmu.Game/Models/Game/Char/Inventory.cs

- when removing armor from a pet's inventory, the character's weapons or clothes appear in the slots.

[Game] Prevents the error of character equipment appearing in pet cells:

---

AAEmu.Game/Models/Game/Units/UnitReqs.cs

- Added a fallback to caster if no target is selected for the TargetBuffTag check. This fixes some glider skills.

[Game] UnitReqs fix for TargetBuffTag if no target is selected

---

AAEmu.Game/Core/Managers/SlaveManager.cs
AAEmu.Game/Core/Managers/UnitManagers/DoodadManager.cs
AAEmu.Game/Core/Packets/C2G/CSStartSkillPacket.cs
AAEmu.Game/GameData/UnitRequirementsGameData.cs
AAEmu.Game/Models/Game/Char/Character.cs
AAEmu.Game/Models/Game/Skills/Plots/Plot.cs
AAEmu.Game/Models/Game/Skills/SkillCaster.cs

- Fixed a bug with ``unit_reqs`` check where in some cases not meeting all requirements would still succeed.
- Cancelling a skill cast item that uses plots no longer locks up the item in your inventory.
- Added a placeholder in ``SkillItem`` SkillCaster for the original item used to start a skill (if any).
This fix closes #1015 - [BUG] Harani mainquest 3541

[Game] Fixed Item with skill usage cancelling

---

AAEmu.Game/Core/Managers/SaveManager.cs
AAEmu.Game/Models/Tasks/ShutdownTask.cs
AAEmu.Game/Scripts/Commands/Scripts.cs

Added a ``/scripts shutdown`` command. Allowed arguments are:
- ``cancel`` to cancel any ongoing shutdown
- ``now`` to shut down immediately
- ``<x>`` to shut down after ``x`` minutes from now
All online players will get a warning of the shutdown request, and will also get warnings at set varying intervals.

[Game] Added shutdown to scripts

---

AAEmu.Game/Models/Game/Quests/NewQuestCode.cs

- Fixed a bug in GetQuestObjectiveStatus that didn't take into account Selective progress.
This fix closes #1022 - [BUG] Quest 6655 - The Key To Regrading - Locking up controls when trying to complete quest.
And likely also some others.

[Game] Fixed a oversight in the final check for quest completion

---

AAEmu.Game/Data/Portal/worldgates.json
AAEmu.Game/Scripts/SubCommands/Doodads/DoodadPositionSubCommand.cs
AAEmu.Game/Scripts/SubCommands/Doodads/DoodadSpawnSubCommand.cs

- Added Mirage Portal to it's 1.x location and moved the modern one underground.
- Added missing Ayanad Library Worldgates in Solis, Cinder and Growlgate. Implemented the target location of the Pirate/PlayerNation worldgate to DS.
- Fixed spawn doodad GM command's rotation parsing.
This closes #1025 - [DATA] Portal for Mirage missing

[Data] Solis Mirage portal and some DS worldgates

---

AAEmu.Game/Models/Game/Skills/Effects/SpecialEffects/SpawnDoodad.cs

- Added a null-check to the skill in the ``SpawnDoodad`` ``SpecialEffectAction`` to take into account doodads created by for example buffs. This stops ``Frigid Tracks ( 11314 )`` from crashing the player.
Likely also fixes some other issues

[Game] Fix null-exception in SpawnDoodad

---

AAEmu.Game/GameData/SphereGameData.cs
AAEmu.Game/Models/Game/World/AreaTrigger.cs
AAEmu.Game/Models/Game/World/SphereQuest.cs
AAEmu.Game/Models/Spheres/Spheres.cs

- Removed the check where it would delete a shape when it's empty. This fixes skills like ``Magic Circle ( 12796 )`` and the ``Frigid Tracks ( 11314 )`` skill's ``Ice Wall ( 833 )`` doodad.
- Added changed ``AreaShape.TriggerConditionId`` to actually use ``AreaSphereTriggerCondition`` instead of uint.

[Game] Removed the empty area check

---

AAEmu.Game/Models/Game/Units/Buffs.cs

- Added a null-check for the ``CheckBuffTag`` function. This fixes a crash with quest ``A Scrumper in Farmer's Clothing ( 3580 )`` where it's referencing a non-existing tag

[Game] Added null-check for CheckBuffTag
